# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-12-17 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helm', '0006_auto_20191014_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartrelease',
            name='valuefile_name',
            field=models.CharField(default='values.yaml', help_text='helm value file name', max_length=64),
        ),
    ]
