# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-03-25 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helm', '0008_chartrelease_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='chartversion',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='chartversionsnapshot',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
