files: ^bcs-app/
fail_fast: true
default_stages: [commit]
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: flake8
    args: [--config=bcs-app/.flake8]
- repo: https://github.com/timothycrosley/isort
  rev: 5.7.0
  hooks:
  - id: isort
    exclude: >
      (?x)^(
          .*/migrations/.*
          | bcs-app/backend/packages/.*
      )$
    additional_dependencies: [toml]
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black
    args: [--config=bcs-app/pyproject.toml]
    exclude: >
      (?x)^(
          .*/migrations/.*
          | bcs-app/backend/packages/.*
      )$
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.0
  hooks:
  -   id: flake8
      args: [--config=bcs-app/.flake8]
      exclude: >
        (?x)^(
            .*/migrations/.*
            | bcs-app/backend/packages/.*
        )$
