// Code generated by go-queryset. DO NOT EDIT.
package models

import (
	"errors"
	"fmt"
	"time"

	"github.com/jinzhu/gorm"
)

// ===== BEGIN of all query sets

// ===== BEGIN of query set AreaQuerySet

// AreaQuerySet is an queryset type for Area
type AreaQuerySet struct {
	db *gorm.DB
}

// NewAreaQuerySet constructs new AreaQuerySet
func NewAreaQuerySet(db *gorm.DB) AreaQuerySet {
	return AreaQuerySet{
		db: db.Model(&Area{}),
	}
}

func (qs AreaQuerySet) w(db *gorm.DB) AreaQuerySet {
	return NewAreaQuerySet(db)
}

// Create is an autogenerated method
// nolint: dupl
func (o *Area) Create(db *gorm.DB) error {
	return db.Create(o).Error
}

// Delete is an autogenerated method
// nolint: dupl
func (o *Area) Delete(db *gorm.DB) error {
	return db.Delete(o).Error
}

// All is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) All(ret *[]Area) error {
	return qs.db.Find(ret).Error
}

// ChineseNameEq is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) ChineseNameEq(chineseName string) AreaQuerySet {
	return qs.w(qs.db.Where("chinese_name = ?", chineseName))
}

// ChineseNameIn is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) ChineseNameIn(chineseName ...string) AreaQuerySet {
	if len(chineseName) == 0 {
		qs.db.AddError(errors.New("must at least pass one chineseName in ChineseNameIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("chinese_name IN (?)", chineseName))
}

// ChineseNameNe is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) ChineseNameNe(chineseName string) AreaQuerySet {
	return qs.w(qs.db.Where("chinese_name != ?", chineseName))
}

// ChineseNameNotIn is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) ChineseNameNotIn(chineseName ...string) AreaQuerySet {
	if len(chineseName) == 0 {
		qs.db.AddError(errors.New("must at least pass one chineseName in ChineseNameNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("chinese_name NOT IN (?)", chineseName))
}

// ConfigurationEq is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) ConfigurationEq(configuration string) AreaQuerySet {
	return qs.w(qs.db.Where("configuration = ?", configuration))
}

// ConfigurationIn is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) ConfigurationIn(configuration ...string) AreaQuerySet {
	if len(configuration) == 0 {
		qs.db.AddError(errors.New("must at least pass one configuration in ConfigurationIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("configuration IN (?)", configuration))
}

// ConfigurationNe is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) ConfigurationNe(configuration string) AreaQuerySet {
	return qs.w(qs.db.Where("configuration != ?", configuration))
}

// ConfigurationNotIn is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) ConfigurationNotIn(configuration ...string) AreaQuerySet {
	if len(configuration) == 0 {
		qs.db.AddError(errors.New("must at least pass one configuration in ConfigurationNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("configuration NOT IN (?)", configuration))
}

// Count is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) Count() (int, error) {
	var count int
	err := qs.db.Count(&count).Error
	return count, err
}

// CreatedAtEq is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) CreatedAtEq(createdAt time.Time) AreaQuerySet {
	return qs.w(qs.db.Where("created_at = ?", createdAt))
}

// CreatedAtGt is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) CreatedAtGt(createdAt time.Time) AreaQuerySet {
	return qs.w(qs.db.Where("created_at > ?", createdAt))
}

// CreatedAtGte is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) CreatedAtGte(createdAt time.Time) AreaQuerySet {
	return qs.w(qs.db.Where("created_at >= ?", createdAt))
}

// CreatedAtLt is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) CreatedAtLt(createdAt time.Time) AreaQuerySet {
	return qs.w(qs.db.Where("created_at < ?", createdAt))
}

// CreatedAtLte is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) CreatedAtLte(createdAt time.Time) AreaQuerySet {
	return qs.w(qs.db.Where("created_at <= ?", createdAt))
}

// CreatedAtNe is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) CreatedAtNe(createdAt time.Time) AreaQuerySet {
	return qs.w(qs.db.Where("created_at != ?", createdAt))
}

// Delete is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) Delete() error {
	return qs.db.Delete(Area{}).Error
}

// DeleteNum is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) DeleteNum() (int64, error) {
	db := qs.db.Delete(Area{})
	return db.RowsAffected, db.Error
}

// DeleteNumUnscoped is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) DeleteNumUnscoped() (int64, error) {
	db := qs.db.Unscoped().Delete(Area{})
	return db.RowsAffected, db.Error
}

// DeletedAtEq is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) DeletedAtEq(deletedAt time.Time) AreaQuerySet {
	return qs.w(qs.db.Where("deleted_at = ?", deletedAt))
}

// DeletedAtGt is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) DeletedAtGt(deletedAt time.Time) AreaQuerySet {
	return qs.w(qs.db.Where("deleted_at > ?", deletedAt))
}

// DeletedAtGte is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) DeletedAtGte(deletedAt time.Time) AreaQuerySet {
	return qs.w(qs.db.Where("deleted_at >= ?", deletedAt))
}

// DeletedAtIsNotNull is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) DeletedAtIsNotNull() AreaQuerySet {
	return qs.w(qs.db.Where("deleted_at IS NOT NULL"))
}

// DeletedAtIsNull is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) DeletedAtIsNull() AreaQuerySet {
	return qs.w(qs.db.Where("deleted_at IS NULL"))
}

// DeletedAtLt is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) DeletedAtLt(deletedAt time.Time) AreaQuerySet {
	return qs.w(qs.db.Where("deleted_at < ?", deletedAt))
}

// DeletedAtLte is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) DeletedAtLte(deletedAt time.Time) AreaQuerySet {
	return qs.w(qs.db.Where("deleted_at <= ?", deletedAt))
}

// DeletedAtNe is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) DeletedAtNe(deletedAt time.Time) AreaQuerySet {
	return qs.w(qs.db.Where("deleted_at != ?", deletedAt))
}

// DescriptionEq is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) DescriptionEq(description string) AreaQuerySet {
	return qs.w(qs.db.Where("description = ?", description))
}

// DescriptionIn is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) DescriptionIn(description ...string) AreaQuerySet {
	if len(description) == 0 {
		qs.db.AddError(errors.New("must at least pass one description in DescriptionIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("description IN (?)", description))
}

// DescriptionNe is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) DescriptionNe(description string) AreaQuerySet {
	return qs.w(qs.db.Where("description != ?", description))
}

// DescriptionNotIn is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) DescriptionNotIn(description ...string) AreaQuerySet {
	if len(description) == 0 {
		qs.db.AddError(errors.New("must at least pass one description in DescriptionNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("description NOT IN (?)", description))
}

// ExtraEq is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) ExtraEq(extra string) AreaQuerySet {
	return qs.w(qs.db.Where("extra = ?", extra))
}

// ExtraIn is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) ExtraIn(extra ...string) AreaQuerySet {
	if len(extra) == 0 {
		qs.db.AddError(errors.New("must at least pass one extra in ExtraIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("extra IN (?)", extra))
}

// ExtraNe is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) ExtraNe(extra string) AreaQuerySet {
	return qs.w(qs.db.Where("extra != ?", extra))
}

// ExtraNotIn is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) ExtraNotIn(extra ...string) AreaQuerySet {
	if len(extra) == 0 {
		qs.db.AddError(errors.New("must at least pass one extra in ExtraNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("extra NOT IN (?)", extra))
}

// GetDB is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) GetDB() *gorm.DB {
	return qs.db
}

// GetUpdater is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) GetUpdater() AreaUpdater {
	return NewAreaUpdater(qs.db)
}

// IDEq is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) IDEq(ID uint) AreaQuerySet {
	return qs.w(qs.db.Where("id = ?", ID))
}

// IDGt is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) IDGt(ID uint) AreaQuerySet {
	return qs.w(qs.db.Where("id > ?", ID))
}

// IDGte is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) IDGte(ID uint) AreaQuerySet {
	return qs.w(qs.db.Where("id >= ?", ID))
}

// IDIn is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) IDIn(ID ...uint) AreaQuerySet {
	if len(ID) == 0 {
		qs.db.AddError(errors.New("must at least pass one ID in IDIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("id IN (?)", ID))
}

// IDLt is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) IDLt(ID uint) AreaQuerySet {
	return qs.w(qs.db.Where("id < ?", ID))
}

// IDLte is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) IDLte(ID uint) AreaQuerySet {
	return qs.w(qs.db.Where("id <= ?", ID))
}

// IDNe is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) IDNe(ID uint) AreaQuerySet {
	return qs.w(qs.db.Where("id != ?", ID))
}

// IDNotIn is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) IDNotIn(ID ...uint) AreaQuerySet {
	if len(ID) == 0 {
		qs.db.AddError(errors.New("must at least pass one ID in IDNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("id NOT IN (?)", ID))
}

// Limit is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) Limit(limit int) AreaQuerySet {
	return qs.w(qs.db.Limit(limit))
}

// NameEq is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) NameEq(name string) AreaQuerySet {
	return qs.w(qs.db.Where("name = ?", name))
}

// NameIn is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) NameIn(name ...string) AreaQuerySet {
	if len(name) == 0 {
		qs.db.AddError(errors.New("must at least pass one name in NameIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("name IN (?)", name))
}

// NameNe is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) NameNe(name string) AreaQuerySet {
	return qs.w(qs.db.Where("name != ?", name))
}

// NameNotIn is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) NameNotIn(name ...string) AreaQuerySet {
	if len(name) == 0 {
		qs.db.AddError(errors.New("must at least pass one name in NameNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("name NOT IN (?)", name))
}

// Offset is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) Offset(offset int) AreaQuerySet {
	return qs.w(qs.db.Offset(offset))
}

// One is used to retrieve one result. It returns gorm.ErrRecordNotFound
// if nothing was fetched
func (qs AreaQuerySet) One(ret *Area) error {
	return qs.db.First(ret).Error
}

// OrderAscByCreatedAt is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) OrderAscByCreatedAt() AreaQuerySet {
	return qs.w(qs.db.Order("created_at ASC"))
}

// OrderAscByDeletedAt is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) OrderAscByDeletedAt() AreaQuerySet {
	return qs.w(qs.db.Order("deleted_at ASC"))
}

// OrderAscByID is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) OrderAscByID() AreaQuerySet {
	return qs.w(qs.db.Order("id ASC"))
}

// OrderAscByUpdatedAt is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) OrderAscByUpdatedAt() AreaQuerySet {
	return qs.w(qs.db.Order("updated_at ASC"))
}

// OrderDescByCreatedAt is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) OrderDescByCreatedAt() AreaQuerySet {
	return qs.w(qs.db.Order("created_at DESC"))
}

// OrderDescByDeletedAt is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) OrderDescByDeletedAt() AreaQuerySet {
	return qs.w(qs.db.Order("deleted_at DESC"))
}

// OrderDescByID is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) OrderDescByID() AreaQuerySet {
	return qs.w(qs.db.Order("id DESC"))
}

// OrderDescByUpdatedAt is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) OrderDescByUpdatedAt() AreaQuerySet {
	return qs.w(qs.db.Order("updated_at DESC"))
}

// UpdatedAtEq is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) UpdatedAtEq(updatedAt time.Time) AreaQuerySet {
	return qs.w(qs.db.Where("updated_at = ?", updatedAt))
}

// UpdatedAtGt is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) UpdatedAtGt(updatedAt time.Time) AreaQuerySet {
	return qs.w(qs.db.Where("updated_at > ?", updatedAt))
}

// UpdatedAtGte is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) UpdatedAtGte(updatedAt time.Time) AreaQuerySet {
	return qs.w(qs.db.Where("updated_at >= ?", updatedAt))
}

// UpdatedAtLt is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) UpdatedAtLt(updatedAt time.Time) AreaQuerySet {
	return qs.w(qs.db.Where("updated_at < ?", updatedAt))
}

// UpdatedAtLte is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) UpdatedAtLte(updatedAt time.Time) AreaQuerySet {
	return qs.w(qs.db.Where("updated_at <= ?", updatedAt))
}

// UpdatedAtNe is an autogenerated method
// nolint: dupl
func (qs AreaQuerySet) UpdatedAtNe(updatedAt time.Time) AreaQuerySet {
	return qs.w(qs.db.Where("updated_at != ?", updatedAt))
}

// SetChineseName is an autogenerated method
// nolint: dupl
func (u AreaUpdater) SetChineseName(chineseName string) AreaUpdater {
	u.fields[string(AreaDBSchema.ChineseName)] = chineseName
	return u
}

// SetConfiguration is an autogenerated method
// nolint: dupl
func (u AreaUpdater) SetConfiguration(configuration string) AreaUpdater {
	u.fields[string(AreaDBSchema.Configuration)] = configuration
	return u
}

// SetCreatedAt is an autogenerated method
// nolint: dupl
func (u AreaUpdater) SetCreatedAt(createdAt time.Time) AreaUpdater {
	u.fields[string(AreaDBSchema.CreatedAt)] = createdAt
	return u
}

// SetDeletedAt is an autogenerated method
// nolint: dupl
func (u AreaUpdater) SetDeletedAt(deletedAt *time.Time) AreaUpdater {
	u.fields[string(AreaDBSchema.DeletedAt)] = deletedAt
	return u
}

// SetDescription is an autogenerated method
// nolint: dupl
func (u AreaUpdater) SetDescription(description string) AreaUpdater {
	u.fields[string(AreaDBSchema.Description)] = description
	return u
}

// SetExtra is an autogenerated method
// nolint: dupl
func (u AreaUpdater) SetExtra(extra string) AreaUpdater {
	u.fields[string(AreaDBSchema.Extra)] = extra
	return u
}

// SetID is an autogenerated method
// nolint: dupl
func (u AreaUpdater) SetID(ID uint) AreaUpdater {
	u.fields[string(AreaDBSchema.ID)] = ID
	return u
}

// SetName is an autogenerated method
// nolint: dupl
func (u AreaUpdater) SetName(name string) AreaUpdater {
	u.fields[string(AreaDBSchema.Name)] = name
	return u
}

// SetUpdatedAt is an autogenerated method
// nolint: dupl
func (u AreaUpdater) SetUpdatedAt(updatedAt time.Time) AreaUpdater {
	u.fields[string(AreaDBSchema.UpdatedAt)] = updatedAt
	return u
}

// Update is an autogenerated method
// nolint: dupl
func (u AreaUpdater) Update() error {
	return u.db.Updates(u.fields).Error
}

// UpdateNum is an autogenerated method
// nolint: dupl
func (u AreaUpdater) UpdateNum() (int64, error) {
	db := u.db.Updates(u.fields)
	return db.RowsAffected, db.Error
}

// ===== END of query set AreaQuerySet

// ===== BEGIN of Area modifiers

// AreaDBSchemaField describes database schema field. It requires for method 'Update'
type AreaDBSchemaField string

// String method returns string representation of field.
// nolint: dupl
func (f AreaDBSchemaField) String() string {
	return string(f)
}

// AreaDBSchema stores db field names of Area
var AreaDBSchema = struct {
	ID            AreaDBSchemaField
	CreatedAt     AreaDBSchemaField
	UpdatedAt     AreaDBSchemaField
	DeletedAt     AreaDBSchemaField
	Extra         AreaDBSchemaField
	Name          AreaDBSchemaField
	Description   AreaDBSchemaField
	Configuration AreaDBSchemaField
	ChineseName   AreaDBSchemaField
}{

	ID:            AreaDBSchemaField("id"),
	CreatedAt:     AreaDBSchemaField("created_at"),
	UpdatedAt:     AreaDBSchemaField("updated_at"),
	DeletedAt:     AreaDBSchemaField("deleted_at"),
	Extra:         AreaDBSchemaField("extra"),
	Name:          AreaDBSchemaField("name"),
	Description:   AreaDBSchemaField("description"),
	Configuration: AreaDBSchemaField("configuration"),
	ChineseName:   AreaDBSchemaField("chinese_name"),
}

// Update updates Area fields by primary key
// nolint: dupl
func (o *Area) Update(db *gorm.DB, fields ...AreaDBSchemaField) error {
	dbNameToFieldName := map[string]interface{}{
		"id":            o.ID,
		"created_at":    o.CreatedAt,
		"updated_at":    o.UpdatedAt,
		"deleted_at":    o.DeletedAt,
		"extra":         o.Extra,
		"name":          o.Name,
		"description":   o.Description,
		"configuration": o.Configuration,
		"chinese_name":  o.ChineseName,
	}
	u := map[string]interface{}{}
	for _, f := range fields {
		fs := f.String()
		u[fs] = dbNameToFieldName[fs]
	}
	if err := db.Model(o).Updates(u).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return err
		}

		return fmt.Errorf("can't update Area %v fields %v: %s",
			o, fields, err)
	}

	return nil
}

// AreaUpdater is an Area updates manager
type AreaUpdater struct {
	fields map[string]interface{}
	db     *gorm.DB
}

// NewAreaUpdater creates new Area updater
// nolint: dupl
func NewAreaUpdater(db *gorm.DB) AreaUpdater {
	return AreaUpdater{
		fields: map[string]interface{}{},
		db:     db.Model(&Area{}),
	}
}

// ===== END of Area modifiers

// ===== END of all query sets
