# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-03-18 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20191217_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='enable_helm',
            field=models.BooleanField(default=False, help_text='如果为True，允许使用helm命名操作chart/release'),
        ),
    ]
