# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-07-24 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_app_enable_helm'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='cmd_flags',
            field=models.TextField(blank=True, default='[]', help_text='命令行参数', null=True),
        ),
    ]
