# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-12-17 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190711_1920'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='app',
            unique_together=set([('namespace_id', 'name', 'unique_ns')]),
        ),
        migrations.AlterIndexTogether(
            name='app',
            index_together=set([('namespace_id', 'name', 'unique_ns')]),
        ),
    ]
