# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-29 08:09
from __future__ import unicode_literals

import backend.apps.configuration.models.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0030_auto_20190221_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='K8sHPA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=32, verbose_name='创建者')),
                ('updator', models.CharField(max_length=32, verbose_name='更新者')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_time', models.DateTimeField(blank=True, null=True)),
                ('config', models.TextField(verbose_name='配置信息')),
                ('name', models.CharField(default='', max_length=255, verbose_name='名称')),
            ],
            options={
                'ordering': ('created',),
                'abstract': False,
            },
            bases=(models.Model, backend.apps.configuration.models.mixins.ResourceMixin),
        )
    ]
