# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-14 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helm', '0005_chartrelease_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartversion',
            name='version',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='chartversionsnapshot',
            name='version',
            field=models.CharField(max_length=255),
        ),
    ]
