# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-04-14 08:35
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('helm', '0009_auto_20200325_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='annotations',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
