# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-02 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0034_auto_20200106_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcefile',
            name='name',
            field=models.TextField(verbose_name='file name'),
        ),
        migrations.AlterField(
            model_name='resourcefile',
            name='resource_name',
            field=models.CharField(choices=[('Deployment', 'Deployment'), ('Service', 'Service'), ('ConfigMap', 'ConfigMap'), ('Secret', 'Secret'), ('Ingress', 'Ingress'), ('StatefulSet', 'StatefulSet'), ('DaemonSet', 'DaemonSet'), ('Job', 'Job'), ('HPA', 'HPA'), ('ServiceAccount', 'ServiceAccount'), ('ClusterRole', 'ClusterRole'), ('ClusterRoleBinding', 'ClusterRoleBinding'), ('PodDisruptionBudget', 'PodDisruptionBudget'), ('StorageClass', 'StorageClass'), ('PersistentVolume', 'PersistentVolume'), ('PersistentVolumeClaim', 'PersistentVolumeClaim'), ('CustomManifest', 'CustomManifest')], max_length=32),
        ),
    ]
