# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-03-09 07:21
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0036_showversion_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='showversion',
            name='revision_history',
            field=jsonfield.fields.JSONField(default=[], verbose_name='历史修订版本记录'),
        ),
    ]
