[tool.black]
line-length = 119
skip-string-normalization = 'true'
exclude = '''
/(
  .*/migrations
)/
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 119
