---
apiVersion: v1
data:
  config: |-
    apiVersion: v1
    clusters:
    - cluster:
        insecure-skip-tls-verify: true
        server: {{ https_server_address }}
      name: {{ source_cluster_id }}
    contexts:
    - context:
        cluster: {{ source_cluster_id }}
        user: {{ username }}
        namespace: default
      name: {{ source_cluster_id }}
    current-context: {{ source_cluster_id }}
    kind: Config
    users:
    - name: {{ username }}
      user:
        token: {{ user_token }}
kind: ConfigMap
metadata:
  name: kube-config-{{ source_cluster_id | lower }}-u{{ username_slug }}