---
apiVersion: v1
kind: Pod
metadata:
  name: kubectld-{{ source_cluster_id | lower }}-u{{ username_slug }}
spec:
    containers:
    - image: {{ settings.WEB_CONSOLE_KUBECTLD_IMAGE_PATH }}:{{ kubectld_version }}
      imagePullPolicy: Always
      name: kubectld-{{ source_cluster_id | lower }}-u{{ username_slug }}
      volumeMounts:
      - name: kube-config
        mountPath: /root/.kube/config
        subPath: config
    volumes:
      - name: kube-config
        configMap:
          name: kube-config-{{ source_cluster_id | lower }}-u{{ username_slug }}
    restartPolicy: Always