# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-04-04 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostApplyTaskLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project_id', models.CharField(max_length=32)),
                ('task_id', models.CharField(max_length=64, null=True)),
                ('task_url', models.CharField(max_length=256, null=True)),
                ('operator', models.CharField(max_length=16, null=True)),
                ('params', jsonfield.fields.JSONField(default={}, null=True)),
                ('status', models.CharField(max_length=32, null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('logs', jsonfield.fields.JSONField(default={}, null=True)),
            ],
        ),
    ]
