# -*- coding: utf-8 -*-
#
# Tencent is pleased to support the open source community by making 蓝鲸智云PaaS平台社区版 (BlueKing PaaS Community Edition) available.
# Copyright (C) 2017-2019 THL A29 Limited, a Tencent company. All rights reserved.
# Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://opensource.org/licenses/MIT
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
# an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.
#
# Generated by Django 1.11.5 on 2018-04-20 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDataInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=32, unique=True, verbose_name='项目ID')),
                ('data_project_id', models.IntegerField(blank=True, null=True, verbose_name='数据平台上申请的项目ID')),
                ('standard_data_id', models.IntegerField(blank=True, null=True, verbose_name='标准日志采集的dataid')),
                ('standard_data_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='标准日志采集源数据')),
                ('standard_flow_id', models.IntegerField(blank=True, null=True, verbose_name='标准日志采集DataFlow ID')),
                ('standard_flow_task_id', models.IntegerField(blank=True, null=True, verbose_name='标准日志采集DataFlow 任务ID')),
                ('non_standard_data_id', models.IntegerField(blank=True, null=True, verbose_name='非标准日志采集的dataid')),
                ('non_standard_data_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='非标准日志采集源数据')),
                ('non_standard_flow_id', models.IntegerField(blank=True, null=True, verbose_name='非标准日志采集DataFlow ID')),
                ('non_standard_flow_task_id', models.IntegerField(blank=True, null=True, verbose_name='非标准日志采集DataFlow 任务ID')),
            ],
        ),
    ]
