---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-test
  namespace: default
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: "/tmp/data"
  storageClassName: fast-storage
