/**
 * Tencent is pleased to support the open source community by making 蓝鲸智云PaaS平台社区版 (BlueKing PaaS Community Edition) available.
 * Copyright (C) 2017-2019 THL A29 Limited, a Tencent company. All rights reserved.
 * Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://opensource.org/licenses/MIT
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */

export default {
    '节点': ['Nodes'],
    '设置标签': ['Set Label'],
    '全部集群': ['All Clusters'],
    '清除': ['Clear'],
    '刷新': ['Refresh'],
    '主机名/IP': ['Hostname/IP'],
    '状态': ['Status'],
    '所属集群': ['Belongs Cluster'],
    '标签': ['Label'],
    '操作': ['Operation'],
    '初始化中': ['initializing'],
    '删除中': ['removing'],
    '展开': ['expand'],
    '收起': ['collapse'],
    '更多操作': ['More Operation'],
    '初始化失败': ['initial failed'],
    '移除失败': ['remove failed'],
    '不可调度': ['Unschedulable'],
    '不正常': ['unnormal'],
    '正常': ['normal'],
    '无数据': ['No Data'],
    '键': ['Key'],
    '值': ['Value'],
    '为什么会有混合值': ['Why are there mixed values'],
    '已选节点的标签中存在同一个键对应多个值': ['The same key corresponds to multiple values in the label of the selected node.'],
    '混合值': ['Mixed value'],
    '保存': ['Save'],
    '取消': ['Cancel'],
    '请选择节点': ['Please Choose Node'],
    '键值【{key}】重复，请重新填写': ['Key value【{key}】is repeated, please re-fill'],
    '没有数据': ['No Data'],
    '确认': ['OK'],
    'IP地址': ['IP Addr'],
    '请输入要搜索的ip，多个ip以 | 隔开': ['Please enter IP to search, multiple IPs separated by |'],
    '请输入要搜索的key': ['Please enter key to search'],
    '请输入要搜索的value': ['Please enter value to search'],
    '集群': ['Clusters'],
    '快速入门': ['Quick Start'],
    '返回': ['Back'],
    '总览': ['Overview'],
    '节点管理': ['Node Manage'],
    '集群信息': ['Cluster Info'],
    '添加节点': ['Add node'],
    '启用Helm': ['Enable Helm'],
    '删除': ['Del'],
    '您需要删除集群内所有节点后，再进行集群删除操作': ['You need to delete all nodes in the cluster before you do the cluster delete'],
    '申请使用权限': ['Apply permission'],
    '正在删除中，请稍等···': ['Deleting'],
    '查看日志': ['Show Log'],
    '删除失败，请重试': ['Delete failed, please try again'],
    '重新删除': ['Re-delete'],
    '正在初始化中，请稍等···': ['Initializing'],
    '初始化失败，请重试': ['Initialization failed, please try again'],
    '恭喜，集群创建成功！': ['Congratulations, Cluster was created successfully!'],
    'CPU使用率': ['CPU Usage'],
    '内存使用率': ['Memory Usage'],
    '磁盘使用率': ['Disk Usage'],
    '点击新建集群': ['Create Cluster'],
    '欢迎使用容器服务': ['Welcome to the BCS'],
    '使用容器服务，蓝鲸将为您快速搭建、运维和管理容器集群，您可以轻松对容器进行启动、停止等操作，也可以查看集群、容器及服务的状态，以及使用各种组件服务。': ['BCS will quickly build, operate, and manage container clusters for you, making it easy to start, stop, and more, as well as view the status of clusters, containers, and services, as well as use a variety of component services.'],
    '请点击了解更多': ['Read More'],
    '创建容器集群': ['Create Cluster'],
    '快速入门指引': ['Quick Start Guide'],
    '暂无日志信息': ['No Log Data'],
    '操作成功': ['Operation Successful'],
    '操作失败': ['Operation failed'],
    '正在加载中...': ['Loading...'],
    '查看详情': ['Show Detail'],
    '点击了解更多': ['Read More'],
    '确定删除集群？': ['Are you sure want to delete the cluster?'],
    '此操作无法撤回，请确认：': ['This operation can\'t be recalled, please confirm:'],
    '确定': ['Ok'],
    '将master主机归还到你业务的空闲机模块': ['Return the master host to your business\'s idle machine module'],
    '清理其它容器服务相关组件': ['Clean up other container service related components'],
    '启用Helm成功': ['Enable Helm successfully'],
    '启用Helm失败': ['Enable Helm failed'],
    '使用中': ['Using'],
    '未使用': ['Unused'],
    '命名空间': ['Namespace'],
    '已使用': ['Used'],
    '总量': ['Total'],
    '批量操作': ['Batch operation'],
    '允许调度': ['Allow schedule'],
    '停止调度': ['Stop schedule'],
    '容器数量': ['Containers'],
    '升序': ['Asc'],
    '降序': ['Desc'],
    '删除失败': ['delete failed'],
    '故障移除': ['Fault removal'],
    '重试': ['Retry'],
    '强制删除': ['Forced delete'],
    '请确保该节点已经没有运行中的容器': ['Make sure the node has no running containers'],
    '更多': ['More'],
    'pod迁移': ['Pod migration'],
    'taskgroup迁移': ['Taskgroup migration'],
    '按照规则修改主机名': ['Modify the host name according to the rules'],
    '安装容器服务相关的组件': ['Install container service related components'],
    '选择服务器': ['Select Server'],
    '请选择服务器': ['Please Select Server'],
    '关联业务：': ['Associated business: '],
    '主机名称': ['Host Name'],
    '内网IP': ['Intranet IP'],
    'Agent状态': ['Agent Status'],
    '您在当前业务下没有主机资源，请联系业务运维': ['You have no host resources under the current service. Please contact the service operation.'],
    '此操作需要对你的主机进行如下操作，请知悉：': ['This operation needs to do the following for your host:'],
    '确定，添加节点': ['Ok'],
    '我再想想': ['Cancel'],
    '删除中...': ['removing'],
    '内存': ['RAM'],
    '磁盘IO': ['Disk IO'],
    '前置检查': ['Pre-inspection'],
    '添加中...': ['Adding'],
    '初始化中...': ['initializing'],
    '启用中...': ['Enable...'],
    '停用中...': ['Disable...'],
    '迁移中...': ['Migration...'],
    '操作中...': ['Operation...'],
    '基本信息': ['Basic Information'],
    '集群名称': ['Cluster name'],
    '请输入集群名称，不超过64个字符': ['Please enter the cluster name, no more than 64 characters'],
    '集群ID': ['Cluster ID'],
    'Master数量': ['Master count'],
    '节点数量': ['Node count'],
    '所属地域': ['Region'],
    '创建时间': ['Create Time'],
    '更新时间': ['Update Time'],
    '集群描述': ['Cluster Desc'],
    '设置变量': ['Set Variable'],
    '配置': ['Configuration'],
    '集群变量': ['Cluster Variable'],
    '变量：': ['Variable: '],
    '请输入集群描述，不超过128个字符': ['Please enter the cluster desc, no more than 120 characters'],
    'Master信息': ['Master Info'],
    '当前节点已被项目（{projectName}）的集群（{clusterName}）占用': ['The current node is already occupied by the cluster（{clusterName}）of the project（{projectName}）'],
    '无匹配的主机资源': ['No matching host resources'],
    '当前访问的页面不存在': ['Currently accessed page does not exist'],
    '当前访问的集群不存在': ['The currently accessed cluster does not exist'],
    'Sorry，您的权限不足!': ['Sorry, your permissions are not enough!'],
    '操作审计': ['Operation Audit'],
    '操作对象类型': ['Operation object type'],
    '操作类型': ['Operation Type'],
    '类型：': ['Type：'],
    '全部1': ['all', '全部'],
    '注意1': ['note', '注意'],
    '创建1': ['add', '创建'],
    '更新1': ['modify', '更新'],
    '删除1': ['delete', '删除'],
    '开始1': ['begin', '开始'],
    '结束1': ['end', '结束'],
    '启动1': ['start', '启动'],
    '暂停1': ['pause', '暂停'],
    '继续1': ['carryon', '继续'],
    '停止1': ['stop', '停止'],
    '重启1': ['restart', '重启'],
    '查询1': ['query', '查询'],
    '未知1': ['unknown', '未知'],
    '完成1': ['completed', '完成'],
    '错误1': ['error', '错误'],
    '处理中1': ['busy', '处理中'],
    '成功1': ['succeed', '成功'],
    '失败1': ['failed', '失败'],
    '查询': ['Search'],
    '时间': ['Time'],
    '对象及类型': ['Object and Type'],
    '发起者': ['Operator'],
    '对象：': ['Object：'],
    '描述': ['Desc'],
    '事件查询': ['Event Query'],
    '事件对象': ['Event Object'],
    '事件级别': ['Event Level'],
    '组件': ['Component'],
    '对象及级别': ['Object&Level'],
    '事件内容': ['Event Content'],
    '级别：': ['Level：'],
    '昨天': ['Yestoday'],
    '最近一周': ['Last week'],
    '最近一个月': ['Last month'],
    '最近三个月': ['Last 3 months'],
    '公共镜像': ['Public Image'],
    '项目镜像': ['Private Image'],
    '如何推镜像？': ['How to push image?'],
    '输入镜像名，按Enter搜索': ['Press Enter to search image name'],
    '来源：': ['Source：'],
    '简介：': ['Introduction：'],
    '详情': ['Details'],
    '次下载': ['downloads'],
    '最近更新人': ['Latest updater'],
    '最近更新时间': ['Latest update time'],
    '仓库相对地址': ['Repo relative address'],
    '名称': ['Name'],
    '大小': ['Size'],
    '地址': ['Address'],
    '没有更多TAG': ['No more TAGs'],
    '主机名称：': ['Hostname：'],
    '主机IP：': ['HostIP：'],
    '容器IP：': ['ContainerIP：'],
    '容器ID：': ['ContainerID：'],
    '镜像：': ['Image：'],
    '网络模式：': ['Network mode：'],
    '网络': ['Network'],
    '存储使用率': ['Disk usage'],
    '端口映射': ['Port Mapping'],
    '该应用的网络模式无需端口映射': ['The application\'s network mode does not require port mapping'],
    '命令': ['command'],
    '挂载卷': ['Mounted volume'],
    '环境变量': ['Env variable'],
    '健康检查': ['Health check'],
    '资源限制': ['Resource limit'],
    '正在加载': ['Loading'],
    '发送': ['Send'],
    '接收': ['Receive'],
    '当前节点上正在运行的容器会被调度到其它可用节点': ['Containers running on the current node are scheduled to other available nodes'],
    '清理容器服务系统组件': ['Clean up container service system components'],
    '仅删除节点的信息记录，需要手动清理节点及其服务': ['Delete only the information record of the node, you need to manually clean up the node and its services.'],
    '确认要重新初始化节点【{innerIp}】？': ['Confirm want to reinitialize the node【{innerIp}】?'],
    '确认要强制删除节点【{innerIp}】？': ['Confirm want to delete the node【{innerIp}】?'],
    '确认要删除节点【{innerIp}】？': ['Confirm want to delete the node【{innerIp}】?'],
    '确认允许调度节点【{innerIp}】？': ['Confirm want to allow schedule the node【{innerIp}】?'],
    '确认要停止调度节点【{innerIp}】？': ['Confirm want to stop schedule the node【{innerIp}】?'],
    '确定删除节点？': ['Confirm want to delete the node?'],
    '确定强制删除节点？': ['Confirm want to delete the node?'],
    '确定移除故障节点：{innerIp}？': ['Confirm to remove the failed node: {innerIp}?'],
    '确定移除故障节点？': ['Confirm to remove the failed node'],
    '确定要对{len}个节点进行{str}操作？': ['Confirm to {str} on {len} nodes?'],
    '请输入集群名称': ['Please enter the cluster name'],
    '必填项，不超过64个字符': ['Required, no more than 64 characters'],
    '集群描述：': ['Desc: '],
    '请输入集群描述': ['Please enter the cluster desc'],
    '必填项，不超过128个字符': ['Required, no more than 128 characters'],
    '选择Master：': ['Select Master: '],
    '已选服务器': ['Selected Server'],
    '序号': ['No.'],
    '注意事项：': ['Notice: '],
    '服务器将按照系统规则修改主机名': ['Server will modify the host name according to the system rules'],
    '修改后': ['After modify'],
    '服务器将安装容器服务相关组件': ['Server will install the container service related components'],
    '请选择奇数个服务器': ['Please select odd number of servers'],
    '移除': ['Del'],
    '名称：': ['Name: '],
    '内存：': ['RAM：'],
    '存储：': ['Disk：'],
    'IP来源：': ['IP Source：'],
    '内核：': ['Core：'],
    '操作系统：': ['OS：'],
    '1小时': ['1hour'],
    '24小时': ['24hours'],
    '近7天': ['Last 7 days'],
    '容器': ['Container'],
    '镜像': ['Image'],
    '容器状态不是running': ['Container status is not running'],
    '异常': ['abnormal'],
    '错误': ['Error'],
    '创建集群': ['Create Cluster'],
    '确定，创建集群': ['Ok'],
    '确定要离开？数据未保存，离开后将会丢失': ['Data is not saved and will be lost after leaving, Are you sure?'],
    '请确认注意事项内容': ['Please confirm the contents of the notice'],
    '下发集群配置中，请稍候...': ['In the cluster configuration, please wait...'],
    '下发集群配置完成': ['The cluster configuration is complete.'],
    '蓝鲸容器服务使用教程': ['BCS Use Tutorial'],
    '本教程将向您简单介绍如何使用蓝鲸容器服务': ['This tutorial will give you a brief introduction to how to use the BCS.'],
    '以下是您操作的主要步骤：': ['Here are the main steps for your operation:'],
    '1、新建集群': ['1. Create Cluster'],
    '点击导航“集群”': ['Click navigation "cluster"'],
    '“新建集群”，需要选择Master节点主机（主机信息来源于CMDB），创建集群，确定创建后，系统将进行集群初始化操作': ['"Create Cluster", you need to select the master node host (the host information comes from the CMDB), create a test cluster or a prod cluster. After the creation is complete, the system will perform the cluster initialization operation.'],
    '2、集群增加Node节点': ['2. Cluster adds Node nodes'],
    '进入指定集群': ['Enter the specified cluster'],
    '节点管理，选择添加节点即可': ['Node Manage, choose to add a node'],
    '3、项目镜像管理': ['3. Private image management'],
    '点击导航“仓库”': ['Click navigation "ImageHub"'],
    '“项目镜像”，按文档“如何推镜像”指引将项目镜像推至仓库': ['"Private Image", push the private image to the ImageHub according to the document "How to push the image" guide'],
    '继续': ['Continue'],
    '关闭': ['Close'],
    '4、创建命名空间': ['4. Create Namespace'],
    '点击导航“命名空间”，新建命名空间，指定命名空间所属集群': ['Click navigation "Namespaces" to create namespace and specify the cluster to which the namespace belongs.'],
    '5、创建模板集': ['5. Create Templateset'],
    '点击导航“模板集”，新建模板集。': ['Click navigation "TemplateSets" to create templateset.'],
    '模板集指您接入容器服务的业务模块所包含的Mesos或Kubernetes资源配置，我们将以模板的形式供您可持续编辑，分版本保存。': ['Templateset refers to the Mesos or Kubernetes resource configuration contained in the business module of your access to the container service. We will provide you with a template for sustainable editing and version saving.'],
    '您可以通过Json或Yaml文件导入的方式将已有服务的资源配置导入模板，再次进行编辑并保存': ['You can import the resource configuration of an existing service into the template by JSON or Yaml file import, edit it again and save it.'],
    '6、模板实例化': ['6. Template instantiation'],
    '保存模板后，点击实例化按钮，选择模板集、具体资源模板以及指定集群的命名空间，系统将生成对应的资源配置文件（Json\Yaml）供您检查。': ['After saving the template, click "instantiation" button, select the templateset, the specific resource template, and the namespace of the specified cluster. The system will generate the corresponding resource configuration file (Json\Yaml) for you to check.'],
    '点击“创建”按钮后，系统将下发资源配置文件到指定集群，创建应用实例。': ['After clicking the "Create" button, the system will deliver the resource configuration file to the specified cluster to create an application instance.'],
    '7、应用实例详情': ['7. Application Instance Details'],
    '点击导航“应用”，您将看到具体的实例信息，可在线做滚动升级、扩缩容等操作。': ['Click navigation "Applications", you will see the specific instance information, you can do online rolling updates, expansion and contraction operations.'],
    '重新初始化': ['Re-initialization'],
    '提示': ['Tip'],
    '执行中': ['Executing'],
    '取消中': ['Cancel'],
    '请输入IP，按Enter搜索': ['Press Enter to search IP'],
    '清空': ['Clear'],
    '搜索': ['Search'],
    '多个IP以空格分开，按回车搜索': ['Multiple IPs are separated by spaces, press Enter to search'],

    '新建': ['Create'],
    '命名空间创建后不可更改': ['Cannot be changed after the namespace is created'],
    '变量': ['Variable'],
    '设置变量值': ['Set variable value'],
    '所属集群：': ['Belongs Cluster：'],
    '请输入': ['Please Enter'],
    '请选择': ['Please Select'],
    '新建命名空间': ['Create Namespace'],
    '请填写命名空间名称': ['Please fill the namespace name'],
    '命名空间名称不得小于2个字符': ['Namespace name must be at least 2 characters'],
    '命名空间名称只能包含小写字母、数字以及连字符(-)，且不能以数字开头': ['Namespace names can only contain lowercase letters, numbers, and hyphens (-), and cannot begin with a number'],
    '请选择所属集群': ['Please select the cluster to which you belong'],
    '修改命名空间：{nsName}': ['Update Namespace: {nsName}'],
    '确定删除命名空间？': ['Confirm want to delete the namespace?'],
    '输入关键字，按Enter搜索': ['Press Enter to search keyword'],
    '集群列表': ['Clusters'],
    '命名空间列表': ['Namespaces'],

    // 变量的使用 $t('test', { vari1: 1, vari2: 2 })
    'test': ['{vari1} ---english--- {vari2}']
}
