/**
 * Tencent is pleased to support the open source community by making 蓝鲸智云PaaS平台社区版 (BlueKing PaaS Community Edition) available.
 * Copyright (C) 2017-2019 THL A29 Limited, a Tencent company. All rights reserved.
 * Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://opensource.org/licenses/MIT
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */

export default {
    '选择运行的集群及命名空间': ['Select cluster and namespace'],
    '请选择模板集版本': ['Please select TemplateSet version'],
    '请选择要实例化的模板': ['Please select template to instantiation'],
    '{nsName}的详细配置': ['Detail config of {nsName}'],
    '确定要进行创建操作？': ['Confirm want to create?'],
    '请选择{key}命名空间的{k}': ['Please select {key} namespace\'s {k}'],
    '{locker}正在操作，您如需编辑请联系{locker}解锁。': ['{locker} in operation，If you need to edit, please contact {locker} to unlock'],
    '正式集群': ['Prod Cluster'],
    '测试集群': ['Test Cluster'],
    '查看对比': ['Show Diff'],
    '命名空间名称': ['Namespace'],
    '应用名称': ['Application'],
    '应用名称：': ['Application：'],
    '模板集名称': ['TemplateSet Name'],
    '关闭全屏': ['Close Fullscreen'],
    '模板：': ['Template：'],
    '模板': ['Template'],
    '实例化': ['Instantiate'],
    '创建人：': ['Creator：'],
    '模板集版本': ['TemplateSet version'],
    '创建后启动实例': ['Launch instance after creation'],
    '预览：': ['Preview：'],
    '未实例化过': ['Not instantiated'],
    '已实例化过': ['Instantiated'],
    '全选': ['SelectAll'],
    '反选': ['InverseSelect'],
    '应用列表': ['Applications'],
    '集群类型': ['ClusterType'],
    '通过Helm Chart、Client、模板集YAML方式创建的应用，请通过命名空间视图查询详情': ['For applications created by the Helm Chart、Client、YAML TemplateSet, please query the details through the namespace view.'],
    '命名空间视图': ['Namespaces'],
    '集群模板视图': ['TemplateSets'],
    '当前版本：': ['Version：'],
    '实例数：': ['Instances：'],
    '更新版本：': ['Update：'],
    '请选择版本': ['Please select version'],
    '模板未引用变量': ['Template not referenced variable'],
    '当前线上配置': ['Online config'],
    '编辑并确定，将更新该配置到线上': ['Edit and confirm will be updated to the online'],
    '重建是指删除应用，然后重新下发线上的配置': ['Rebuilding means delete app and then re-delivering the configuration on the line.'],
    '版本': ['Version'],
    '版本号1': ['Tag', '版本'],
    '新增命名空间': ['Add Namespace'],
    '节点': ['Nodes'],
    '设置标签': ['Set Label'],
    '复制IP': ['Copy IP'],
    '复制所选IP': ['Copy Selected IP'],
    '复制当前页IP': ['Copy Page IP'],
    '复制所有IP': ['Copy All IP'],
    '复制所有IP成功': ['Copy All IP Success'],
    '复制当前页IP成功': ['Copy Page IP Success'],
    '复制 {len} 个IP成功': ['Copy {len} IP Success'],
    '全部集群': ['All Clusters'],
    '清除': ['Clear'],
    '刷新': ['Refresh'],
    '主机名/IP': ['Hostname/IP'],
    '状态': ['Status'],
    '所属集群': ['Cluster'],
    '标签': ['Label'],
    '操作': ['Operation'],
    '初始化中': ['initializing'],
    '删除中': ['removing'],
    '展开': ['expand'],
    '收起': ['collapse'],
    '更多操作': ['More Operation'],
    '初始化失败': ['initial failed'],
    '移除失败': ['remove failed'],
    '不可调度': ['Unschedulable'],
    '不正常': ['Unnormal'],
    '正常': ['Normal'],
    '无数据': ['No Data'],
    '键': ['Key'],
    '值': ['Value'],
    '为什么会有混合值': ['Why are there mixed values'],
    '已选节点的标签中存在同一个键对应多个值': ['The same key corresponds to multiple values in the label of the selected node.'],
    '混合值': ['Mixed value'],
    '保存': ['Save'],
    '取消': ['Cancel'],
    '请选择节点': ['Please Choose Node'],
    '键值【{key}】重复，请重新填写': ['Key value【{key}】is repeated, please re-fill'],
    '没有数据': ['No Data'],
    '确认': ['OK'],
    'IP地址': ['IP Addr'],
    '请输入要搜索的ip，多个ip以 | 隔开': ['Please enter IP to search, multiple IPs separated by |'],
    '请输入要搜索的key': ['Please enter key to search'],
    '请输入要搜索的value': ['Please enter value to search'],
    '集群': ['Clusters'],
    '快速入门': ['Quick Start'],
    '返回': ['Back'],
    '总览': ['Overview'],
    '节点管理': ['Node Manage'],
    '集群信息': ['Cluster Info'],
    '添加节点': ['Add node'],
    '启用Helm': ['Enable Helm'],
    '删除': ['Delete'],
    '您需要删除集群内所有节点后，再进行集群删除操作': ['You need to delete all nodes in the cluster before you do the cluster delete'],
    '申请使用权限': ['Apply permission'],
    '正在删除中，请稍等···': ['Deleting'],
    '查看日志': ['Show Log'],
    '删除失败，请重试': ['Delete failed, please try again'],
    '重新删除': ['Re-delete'],
    '正在初始化中，请稍等···': ['Initializing'],
    '初始化失败，请重试': ['Initialization failed, please try again'],
    '恭喜，集群创建成功！': ['Congratulations, Cluster was created successfully!'],
    'CPU使用率': ['CPU Usage'],
    'CPU占集群使用率': ['CPU Usage for cluster'],
    '内存使用率': ['Memory Usage'],
    '内存使用量': ['Memory Usage'],
    '内存占集群使用率': ['Memory Usage for cluster'],
    '容器requests cpu占集群的使用率': ['Container requests cpu accounted for cluster usage'],
    '容器requests 内存占集群的使用率': ['Container requests memory accounted for cluster usage'],
    '磁盘使用率': ['Disk Usage'],
    '点击新建集群': ['Create Cluster'],
    '欢迎使用容器服务': ['Welcome to the BCS'],
    '使用容器服务，蓝鲸将为您快速搭建、运维和管理容器集群，您可以轻松对容器进行启动、停止等操作，也可以查看集群、容器及服务的状态，以及使用各种组件服务。': ['BCS will quickly build, operate, and manage container clusters for you, making it easy to start, stop, and more, as well as view the status of clusters, containers, and services, as well as use a variety of component services.'],
    '请点击了解更多': ['Read More'],
    '创建容器集群': ['Create Cluster'],
    '快速入门指引': ['Quick Start Guide'],
    '暂无日志信息': ['No Log Data'],
    '操作成功': ['Operation Successful'],
    '操作失败': ['Operation failed'],
    '正在加载中...': ['Loading...'],
    '查看详情': ['Show Detail'],
    '点击了解更多': ['Read More'],
    '确定删除集群？': ['Are you sure want to delete the cluster?'],
    '此操作无法撤回，请确认：': ['This operation can\'t be recalled, please confirm:'],
    '确定': ['Ok'],
    '将master主机归还到你业务的空闲机模块': ['Return the master host to your business\'s idle machine module'],
    '清理其它容器服务相关组件': ['Clean up other container service related components'],
    '启用Helm成功': ['Enable Helm successfully'],
    '启用Helm失败': ['Enable Helm failed'],
    '使用中': ['Using'],
    '未使用': ['Unused'],
    '命名空间': ['Namespace'],
    '已使用': ['Used'],
    '总量': ['Total'],
    '批量操作': ['Batch operation'],
    '允许调度': ['Allow schedule'],
    '停止调度': ['Stop schedule'],
    '容器数量': ['Containers'],
    '升序': ['Asc'],
    '降序': ['Desc'],
    '删除失败': ['delete failed'],
    '故障移除': ['Fault removal'],
    '重试': ['Retry'],
    '强制删除': ['Forced delete'],
    '请确保该节点已经没有运行中的容器': ['Make sure the node has no running containers'],
    '更多': ['More'],
    'pod迁移': ['Pod migration'],
    'taskgroup迁移': ['Taskgroup migration'],
    '按照规则修改主机名': ['Modify the host name according to the rules'],
    '安装容器服务相关的组件': ['Install container service related components'],
    '选择服务器': ['Select Host'],
    '请选择服务器': ['Please Select Host'],
    '关联业务：': ['Associated business: '],
    '主机名称': ['Host Name'],
    '内网IP': ['Inner IP'],
    'Agent状态': ['Agent Status'],
    '您在当前业务下没有主机资源，请联系业务运维': ['You have no host resources under the current service. Please contact the service operation.'],
    '此操作需要对你的主机进行如下操作，请知悉：': ['This operation needs to do the following for your host:'],
    '确定，添加节点': ['Ok'],
    '我再想想': ['Cancel'],
    '删除中...': ['removing'],
    '内存': ['RAM'],
    '磁盘IO': ['Disk IO'],
    '磁盘': ['Disk'],
    '前置检查': ['Pre-inspection'],
    '添加中...': ['Adding'],
    '初始化中...': ['initializing'],
    '启用中...': ['Enable...'],
    '停用中...': ['Disable...'],
    '迁移中...': ['Migration...'],
    '操作中...': ['Operation...'],
    '基本信息': ['Basic Information'],
    '集群名称': ['Cluster Name'],
    '请输入集群名称，不超过64个字符': ['Please enter the cluster name, no more than 64 characters'],
    '集群ID': ['Cluster ID'],
    'Master数量': ['Master count'],
    '节点数量': ['Node count'],
    '所属地域': ['Region'],
    '创建时间': ['Create Time'],
    '更新时间': ['Update Time'],
    '集群描述': ['Cluster Desc'],
    '设置变量': ['Set Variable'],
    '配置': ['Configuration'],
    '集群变量': ['Cluster Variable'],
    '变量：': ['Variable: '],
    '请输入集群描述，不超过128个字符': ['Please enter the cluster desc, no more than 120 characters'],
    'Master信息': ['Master Info'],
    '当前节点已被项目（{projectName}）的集群（{clusterName}）占用': ['The current node is already occupied by the cluster（{clusterName}）of the project（{projectName}）'],
    '无匹配的主机资源': ['No matching host resources'],
    '当前访问的页面不存在': ['Currently accessed page does not exist'],
    '当前访问的集群不存在': ['The currently accessed cluster does not exist'],
    'Sorry，您的权限不足!': ['Sorry, your permissions are not enough!'],
    '操作审计': ['Operation Audit'],
    '操作对象类型': ['Operation object type'],
    '操作类型': ['Operation Type'],
    '类型：': ['Type：'],
    '全部1': ['all', '全部'],
    '注意1': ['note', '注意'],
    '创建1': ['add', '创建'],
    '更新1': ['modify', '更新'],
    '删除1': ['delete', '删除'],
    '开始1': ['begin', '开始'],
    '结束1': ['end', '结束'],
    '启动1': ['start', '启动'],
    '暂停1': ['pause', '暂停'],
    '继续1': ['carryon', '继续'],
    '停止1': ['stop', '停止'],
    '重启1': ['restart', '重启'],
    '查询1': ['query', '查询'],
    '未知1': ['unknown', '未知'],
    '完成1': ['completed', '完成'],
    '错误1': ['error', '错误'],
    '处理中1': ['busy', '处理中'],
    '成功1': ['succeed', '成功'],
    '失败1': ['failed', '失败'],
    '查询': ['Search'],
    '时间': ['Time'],
    '对象及类型': ['Object and Type'],
    '发起者': ['Operator'],
    '对象：': ['Object：'],
    '描述': ['Desc'],
    '事件查询': ['Event Query'],
    '事件对象': ['Event Object'],
    '事件级别': ['Event Level'],
    '组件': ['Component'],
    '对象及级别': ['Object&Level'],
    '事件内容': ['Event Content'],
    '级别：': ['Level：'],
    '昨天': ['Yestoday'],
    '最近一周': ['Last week'],
    '最近一个月': ['Last month'],
    '最近三个月': ['Last 3 months'],
    '公共镜像': ['Public Image'],
    '项目镜像': ['Private Image'],
    '如何推镜像？': ['How to push image?'],
    '输入镜像名，按Enter搜索': ['Press Enter to search image name'],
    '来源：': ['Source：'],
    '简介：': ['Introduction：'],
    '详情': ['Details'],
    '次下载': ['downloads'],
    '最近更新人': ['Latest updater'],
    '最近更新时间': ['Latest update time'],
    '仓库相对地址': ['Repo relative address'],
    '名称': ['Name'],
    '大小': ['Size'],
    '地址': ['Address'],
    '没有更多TAG': ['No more TAGs'],
    '主机名称：': ['Hostname：'],
    '主机IP：': ['HostIP：'],
    '容器IP：': ['ContainerIP：'],
    '容器ID：': ['ContainerID：'],
    '镜像：': ['Image：'],
    '网络模式：': ['Network mode：'],
    '网络': ['Network'],
    '存储使用率': ['Disk usage'],
    '端口映射': ['Port Mapping'],
    '该应用的网络模式无需端口映射': ['The application\'s network mode does not require port mapping'],
    '命令': ['command'],
    '挂载卷': ['Mounted volume'],
    '环境变量': ['Env variable'],
    '健康检查': ['Health check'],
    '资源限制': ['Resource limit'],
    '正在加载': ['Loading'],
    '发送': ['Send'],
    '接收': ['Receive'],
    '当前节点上正在运行的容器会被调度到其它可用节点': ['Containers running on the current node are scheduled to other available nodes'],
    '清理容器服务系统组件': ['Clean up container service system components'],
    '仅删除节点的信息记录，需要手动清理节点及其服务': ['Delete only the information record of the node, you need to manually clean up the node and its services.'],
    '确认要重新初始化节点【{innerIp}】？': ['Confirm want to reinitialize the node【{innerIp}】?'],
    '确认要强制删除节点【{innerIp}】？': ['Confirm want to delete the node【{innerIp}】?'],
    '确认要删除节点【{innerIp}】？': ['Confirm want to delete the node【{innerIp}】?'],
    '确认允许调度节点【{innerIp}】？': ['Confirm want to allow schedule the node【{innerIp}】?'],
    '确认要停止调度节点【{innerIp}】？': ['Confirm want to stop schedule the node【{innerIp}】?'],
    '确定删除节点？': ['Confirm want to delete the node?'],
    '确定强制删除节点？': ['Confirm want to delete the node?'],
    '确定移除故障节点：{innerIp}？': ['Confirm to remove the failed node: {innerIp}?'],
    '确定移除故障节点？': ['Confirm to remove the failed node'],
    '重置': ['Reset'],
    '请输入集群名称': ['Please enter the cluster name'],
    '必填项，不超过64个字符': ['Required, no more than 64 characters'],
    '集群描述：': ['Desc: '],
    '请输入集群描述': ['Please enter the cluster desc'],
    '必填项，不超过128个字符': ['Required, no more than 128 characters'],
    '选择Master：': ['Select Master: '],
    '已选服务器': ['Selected Host'],
    '序号': ['No.'],
    '注意事项：': ['Notice: '],
    '服务器将按照系统规则修改主机名': ['Server will modify the host name according to the system rules'],
    '修改后': ['After Modify'],
    '服务器将安装容器服务相关组件': ['Server will install the container service related components'],
    '请选择奇数个服务器': ['Please select odd number of servers'],
    '移除': ['Delete'],
    '名称：': ['Name: '],
    '内存：': ['RAM：'],
    '存储：': ['Disk：'],
    'IP来源：': ['IP Source：'],
    '内核：': ['Core：'],
    '操作系统：': ['OS：'],
    '1小时': ['1hour'],
    '24小时': ['24hours'],
    '近7天': ['Last 7 days'],
    '容器': ['Container'],
    '镜像': ['Image'],
    '容器状态不是running': ['Container status is not running'],
    '异常': ['abnormal'],
    '错误': ['Error'],
    '创建集群': ['Create Cluster'],
    '确定，创建集群': ['Ok'],
    '确定要离开？数据未保存，离开后将会丢失': ['Data is not saved and will be lost after leaving, Are you sure?'],
    '请确认注意事项内容': ['Please confirm the contents of the notice'],
    '下发集群配置中，请稍候...': ['In the cluster configuration, please wait...'],
    '下发集群配置完成': ['The cluster configuration is complete.'],
    '蓝鲸容器服务使用教程': ['BCS Use Tutorial'],
    '本教程将向您简单介绍如何使用蓝鲸容器服务': ['This tutorial will give you a brief introduction to how to use the BCS.'],
    '以下是您操作的主要步骤：': ['Here are the main steps for your operation:'],
    '1、新建集群': ['1. Create Cluster'],
    '点击导航“集群”': ['Click navigation "cluster"'],
    '“新建集群”，需要选择Master节点主机（主机信息来源于CMDB），创建集群，确定创建后，系统将进行集群初始化操作': ['"Create Cluster", you need to select the master node host (the host information comes from the CMDB), create a test cluster or a prod cluster. After the creation is complete, the system will perform the cluster initialization operation.'],
    '2、集群增加Node节点': ['2. Cluster adds Node nodes'],
    '进入指定集群': ['Enter the specified cluster'],
    '节点管理，选择添加节点即可': ['Node Manage, choose to add a node'],
    '3、项目镜像管理': ['3. Private image management'],
    '点击导航“仓库”': ['Click navigation "ImageHub"'],
    '“项目镜像”，按文档“如何推镜像”指引将项目镜像推至仓库': ['"Private Image", push the private image to the ImageHub according to the document "How to push the image" guide'],
    '继续': ['Continue'],
    '关闭': ['Close'],
    '4、创建命名空间': ['4. Create Namespace'],
    '点击导航“命名空间”，新建命名空间，指定命名空间所属集群': ['Click navigation "Namespaces" to create namespace and specify the cluster to which the namespace belongs.'],
    '5、创建模板集': ['5. Create Templateset'],
    '点击导航“模板集”，新建模板集。': ['Click navigation "TemplateSets" to create templateset.'],
    '模板集指您接入容器服务的业务模块所包含的Mesos或Kubernetes资源配置，我们将以模板的形式供您可持续编辑，分版本保存。': ['Templateset refers to the Mesos or Kubernetes resource configuration contained in the business module of your access to the container service. We will provide you with a template for sustainable editing and version saving.'],
    '您可以通过Json或Yaml文件导入的方式将已有服务的资源配置导入模板，再次进行编辑并保存': ['You can import the resource configuration of an existing service into the template by JSON or Yaml file import, edit it again and save it.'],
    '6、模板实例化': ['6. Template instantiation'],
    '保存模板后，点击实例化按钮，选择模板集、具体资源模板以及指定集群的命名空间，系统将生成对应的资源配置文件（Json\Yaml）供您检查。': ['After saving the template, click "instantiation" button, select the templateset, the specific resource template, and the namespace of the specified cluster. The system will generate the corresponding resource configuration file (Json\Yaml) for you to check.'],
    '点击“创建”按钮后，系统将下发资源配置文件到指定集群，创建应用实例。': ['After clicking the "Create" button, the system will deliver the resource configuration file to the specified cluster to create an application instance.'],
    '7、应用实例详情': ['7. Application Instance Details'],
    '点击导航“应用”，您将看到具体的实例信息，可在线做滚动升级、扩缩容等操作。': ['Click navigation "Applications", you will see the specific instance information, you can do online rolling updates, expansion and contraction operations.'],
    '重新初始化': ['Re-initialization'],
    '提示': ['Tip'],
    '执行中': ['Executing'],
    '取消中': ['Cancel'],
    '请输入IP，按Enter搜索': ['Press Enter to search IP'],
    '清空': ['Clear'],
    '搜索': ['Search'],
    '多个IP以空格分开，按回车搜索': ['Multiple IPs are separated by spaces, press Enter to search'],

    '新建': ['Create'],
    '命名空间创建后不可更改': ['Not changed after created'],
    '变量': ['Variable'],
    '设置变量值': ['Set variable value'],
    '所属集群：': ['Cluster：'],
    '请选择': ['Please Select'],
    '新建命名空间': ['Create Namespace'],
    '请填写命名空间名称': ['Please fill the namespace name'],
    '命名空间名称不得小于2个字符': ['Namespace name must be at least 2 characters'],
    '命名空间名称只能包含小写字母、数字以及连字符(-)，且不能以数字开头': ['Namespace names can only contain lowercase letters, numbers, and hyphens (-), and cannot begin with a number'],
    '请选择所属集群': ['Please select the cluster to which you belong'],
    '修改命名空间：{nsName}': ['Update Namespace: {nsName}'],
    '确定删除命名空间？': ['Confirm want to delete the namespace?'],
    '输入关键字，按Enter搜索': ['Press Enter to search keyword'],
    '集群列表': ['Clusters'],
    '命名空间列表': ['Namespaces'],
    '删除命名空间': ['Delete namespace'],
    '删除Namespace将销毁Namespace下的所有资源，销毁后所有数据将被清除且不可恢复，请提前备份好数据。': ['Delete Namespace will destroy all resources under the Namespace. Then all data will be cleared and cannot be restored. Please backup the data.'],
    '集群就绪后，您可以创建命名空间、推送项目镜像到仓库，然后通过服务配置模板集或使用Helm部署服务': ['Once the cluster is ready, you can create a namespace, push the project image to the repository, then configure the template set through the service or deploy the service using Helm'],
    '集群就绪后，您可以创建命名空间、推送项目镜像到仓库，然后通过服务配置模板集部署服务': ['Once the cluster is ready, you can create a namespace, push the project image to the warehouse, and then deploy the service through the service configuration templateset'],

    'HPA管理': ['HPA Manage'],
    '批量删除': ['Batch Delete'],
    '当前': ['Current'],
    '目标': ['Target'],
    '实例数': ['Instances'],
    '范围': ['Scope'],
    '关联资源': ['Relevant resource'],
    '来源': ['Source'],
    '创建人': ['Creator'],
    '已选': ['Selected'],
    '条': ['Item'],
    '确定要删除以下': ['Sure you want to delete'],
    '请选择要删除的HPA！': ['Please choose to delete the HPA!'],
    '确定要删除HPA': ['Sure you want to delete HPA!'],
    '删除成功': ['Successfully delete'],

    'Service名称': ['Service Name'],
    'Service类型': ['Service Type'],
    '更新人': ['Modifier'],
    '关联标签': ['Relevant Label'],
    '请选择要关联的Application': ['Please select the Associated App'],
    '请关联相应的Application': ['Please associate app'],
    '协议': ['Protocol'],
    '端口名称': ['Port Name'],
    '目标端口': ['Target Port'],
    '点此': ['Click this'],
    '去模板集配置端口映射信息': [' to Templateset setting port mapping'],
    '请关联相应的应用': ['Please associate app'],
    '请选择要关联的应用': ['Please associate app'],
    '标签管理': ['Label Manage'],
    '备注管理': ['Remark Manage'],
    '保存并更新': ['Save and update'],
    '请先关联应用': ['Please associate app'],
    '关联的应用没有公共的标签（注：Key、Value都相同的标签为公共标签）': ['There is no public label for associated app (ps: Key、Value all same are the public label)'],
    '基础信息': ['Basic information'],
    '选择器': ['Selector'],
    '确定要删除以下Service？': ['Sure you want to delete Service?'],
    '更新Service': ['Update Service'],
    'ClusterIP不为None时，请配置相应的端口映射': ['ClusterIP is not None, please setting your port mapping'],
    '端口不能为空': ['Port can not be empty'],
    '请选择协议': ['Please select protocol'],
    '端口名称以小写字母开头，只能包含：小写字母、数字、连字符(-)，长度小于30个字符': [''],
    'NodePort的范围为30000-32767': ['The range is 30000-32767 for NodePort'],
    '确定要删除Service': ['Sure you want to delete Service'],

    '权重设置': ['Weight Setting'],
    '服务端口': ['Service Port'],
    '域名': ['Domain'],
    '路径': ['Path'],
    '关联LoadBalance': ['Associate LoadBalance'],
    '没有相关联的 LoadBalance，请先到 网络 -> LoadBalance 页面关联': ['if there is no LoadBalance, please go Network/LoadBalance to setting'],
    '端口索引': ['Port Index'],
    '权重的值为大于等于0的整数，且所有权重相加为100': ['The weight is an integer greater than or equal to 0, and the weights are added to 100.'],
    '服务端口不能为空': ['Service port cannot be empty'],
    '服务端口范围为1-65535': ['Service port range is 1-65535'],
    '请填写正确的路径': ['Please fill in the correct path'],
    '请选择需要关联的LoadBalance': ['Please select the LoadBalance you need to associate'],
    '负载均衡算法': ['Load Balancing Algorithm'],

    '新建LoadBalance': ['New LoadBalance'],
    '网络类型': ['Network Type'],
    '转发模式': ['Forwarding Mode'],
    'IP集': ['IP Set'],
    '镜像地址': ['Image Address'],
    '镜像版本': ['Image Version'],
    '实例数量': ['Instances Number'],
    '调度约束': ['Scheduling Constraint'],
    '多个值以管道符分隔': ['Multiple values ​​separated by pipe'],
    '网络模式': ['Network Mode'],
    '自定义值': ['Custom value'],
    '网卡': ['Network Card'],
    '编辑LoadBalance': ['Edit LoadBalance'],
    '确定要启动此LoadBalance': ['Sure to start this LoadBalance'],
    '已经将配置文件下发到后台，请稍后再详情中查看': ['he configuration file has been delivered to the background, please check the details later'],
    '确定要停止此LoadBalance': ['Sure to stop this LoadBalance'],
    '确定要删除LoadBalance': ['Sure to delete this LoadBalance'],
    '名称错误，只能包含：小写字母、数字、连字符(-)，必须是字母开头，长度小于30个字符': ['The name is incorrect and can only contain: lowercase letters, numbers, hyphens (-), must be at the beginning of the letter, and the length is less than 30 characters'],
    '请选择镜像版本': ['Please select the image version'],
    '请输入正确IP地址': ['Please enter the correct IP address'],
    'IP数量和实例数量不相等': ['The number of IPs and the number of instances are not equal'],
    '请填写实例数量！': ['Please enter the instances number'],
    '请填写网卡': ['Please enter network card'],
    'BRIDGE网络模式下，端口必填': ['In BRIDGE network mode, the port is required'],
    '数据保存成功': ['The data is saved successfully'],
    '查看': ['View'],
    '停止': ['Stop'],
    '启动': ['Start'],
    '编辑': ['Edit'],
    '流量': ['Flow'],
    '入带宽': ['Incoming Bandwidth'],
    '出带宽': ['Outgoing Bandwidth'],
    '所属namespace': ['Namespace'],
    '调度约束规则': ['Constraint Rule'],
    '映射Taskgroup': ['Map Taskgroup'],
    '设置协议': ['Setting Protocol'],
    '至少有一个勾选': ['At least one check'],
    '启用Http': ['Use Http'],
    '启用Https': ['Use Https'],
    '节点IP': ['Node IP'],
    '确定要删除LoadBalance？': ['Sure to delete this LoadBalance?'],
    '请选择命名空间': ['Please select Namespace'],
    '请输入http端口': ['Please enter http port'],
    '请输入https端口': ['Please enter http ports'],
    '请添加节点': ['Please add a node'],

    '输入命名空间，按Enter搜索': ['Enter namespace and press Enter'],

    // helm
    'Helm Release列表': ['Helm Release'],
    '如何使用Helm？': ['How to use Helm?'],
    '部署Helm Chart': ['Deploy Helm Chart'],
    '模板集默认图标': ['Icon'],
    '图标': ['Icon'],
    'Release名称': ['Release Name'],
    '操作记录': ['Operation Record'],
    '查看状态': ['View'],
    '回滚': ['Rollback'],
    '回滚到版本': ['Rollback version'],
    '（Release当前没有可切换的版本，无法回滚）': ['(Release currently has no switchable version and cannot be rolled back)'],
    '版本对比': ['Version comparison'],
    '更新中...': ['Updating...'],
    '知道了': ['Got it'],
    '实际实例数/期望数': ['instances Actual/expected'],
    '部署': ['Deploy'],
    '确定要删除Release？': ['Sure to delete Release?'],
    '失败': [' failure'],
    '部署时间': ['Deploy Time'],
    '回滚失败': ['Rollback failure'],
    '与当前线上版本没有内容差异': ['No content difference from current online version'],
    'Helm Chart仓库': ['Helm Chart Repo'],
    '如何推送Helm Chart到项目仓库？': ['How to push Helm Chart to the project repo?'],
    '项目Chart仓库地址': ['Project Chart Repo Address'],
    '同步仓库': ['Sync Repo'],
    '同步仓库中的Helm Chart 到蓝盾': ['Sync Repo Helm Chart'],
    '查看项目Chart仓库配置信息': ['View project Chart repo configuration'],
    '项目仓库': ['Project Repo'],
    '公共仓库': ['Public Repo'],
    'Helm Chart名称': ['Helm Chart Name'],
    '最近更新': ['Latest Update'],
    '无数据，请尝试': ['No data, please retry'],
    '同步成功': ['The synchronization is successful'],
    '项目Chart仓库配置信息': ['Project Chart Repo Configuration'],
    'Chart详情': ['Chart Detail'],
    'Chart版本': ['Chart Version'],
    '资源文件': ['Resource File'],
    '详细说明': ['Detailed description'],
    'Chart部署': ['Chart Deploy'],
    '查看Chart详情': ['Chart Detail'],
    '配置选项': ['Configuration Option'],
    'Helm参数': ['Helm Params'],
    'YAML初始值为创建时Chart中values.yaml内容，后续更新部署以该YAML内容为准，YAML内容最终通过`--values`选项传递给`helm template`命令': ['The initial value of YAML is the values.yaml content in Chart at the time of creation. The subsequent update deployment is based on the YAML content. The YAML content is finally passed to the `helm template` command through the `values` option.'],
    '表单根据Chart中questions.yaml生成，表单修改后的数据会自动同步给YAML模式': ['Forms are generated according to questions.yaml in Chart, and the modified data automatically synchronizes to YAML mode.'],
    '您可以参考': ['You can refer to this '],
    '指引': ['guide'],
    '通过表单模式配置您的Helm Release 参数': ['Configure your Helm Release parameters through form mode'],
    '也可以通过': ['It can also be passed through'],
    'Yaml模式': ['YAML Mode'],
    'YAML模式': ['YAML Mode'],
    '直接修改Helm Release参数': ['modify Helm Release parameters'],
    '预览': ['Preview'],
    '您需要': ['Your need'],
    '在集群页面，启用Helm': ['On the cluster page, enable Helm'],
    '或者联系': ['or contact'],
    '您可以': ['Your can'],
    '检查Helm Chart是否存在语法错误': ['Check Helm Chart for grammatical errors'],
    '前往Helm Release列表页面，更新Helm Release': ['Go to the Helm Release list page and update Helm Release'],
    '更新Helm Chart，并推送到项目Chart仓库': ['Update Helm Chart and push it to Project Chart Repo'],
    '请输入YAML': ['Please enter YAML'],
    '请输入合法的YAML': ['Please enter correct YAML'],
    '已部署': ['Deployed'],
    '部署失败': ['Deployment failure'],
    '预览失败': ['Preview failure'],
    '不存在': ['Non existent'],
    'Release参数与选中的Chart Version中values.yaml有区别': ['Release parameter is different from values.yaml in the selected Chart Version'],
    'YAML初始值为创建时Chart中values.yaml内容，后续更新部署以该YAML内容为准，内容最终通过`--values`选项传递给`helm template`命令': ['The initial value of YAML is the values.yaml content in Chart at the time of creation. The subsequent update deployment is based on the YAML content. The content is finally passed to the `helm template` command through the `values` option'],
    '您更改了Chart版本，': ['You changed the Chart version. '],
    '点击查看': ['Click to view'],
    'Helm Release参数与选中的Chart Version中values.yaml区别': ['The Helm Release parameter differs from values.yaml in the selected Chart Version'],
    '所属命名空间不存在，不可操作': ['Namespace does not exist and is not operable'],
    'Helm Release参数发生如下变化，请确认后再点击“确定”更新': ['The Helm Release parameter changes as follows. Please confirm and then click OK to update'],
    '本次更新没有内容变化': ['There is no change in the content of this update'],
    '温馨提示：Helm Chart 版本已更改，请检查是否需要同步容器服务上Release 的参数': ['Warm Tip: The Helm Chart version has been changed. Check if you need to sync Release parameters on Container Services'],
    '重新更新': ['Try update'],
    '当前 Release 参数': ['Current Release parameters'],
    'Chart 默认值': ['Chart default'],
    '和当前版本对比': ['Comparing with the current version'],
    '确认更新': ['Confirm update'],
    '更新失败': ['Update failed'],
    'Chart渲染失败': ['Chart rendering failed'],
    '模板集': ['TemplateSets'],
    '添加模板集': ['Add TemplateSet'],
    '最新版本': ['Latest Version'],
    '模板集为草稿状态，不能实例化': ['TemplateSet are in draft state and cannot be instantiated'],
    '复制模板集': ['Copy TemplateSet'],
    '删除模板集': ['Delete TemplateSet'],
    '删除实例': ['Delete Instance'],
    '全部数据加载完成': ['Complete loading of all data'],
    '复制为': ['Copy to'],
    '新模板集名称': ['TemplateSet name'],
    '复制中...': ['Copy...'],
    '没有命名空间数据': ['No namespace data'],
    '没有命名空间': ['No namespace data'],
    '有': ['Has'],
    '个实例': ['Instances'],
    '您需要先删除所有实例，再进行模板集删除操作': ['You need to delete all instances before you delete the TemplateSet'],
    '确定要删除模板集': ['Sure to delete this TemplateSet'],
    '请填写要复制的名称': ['Please enter the name'],
    '复制的名称不能与之前的名称相同': ['The name cannot be the same as the previous'],
    '名称不得大于30个字符': ['Name must not exceed 30 characters'],
    '复制成功': ['Copy Successfully'],
    '模板集的实例': ['instances'],
    '获取项目信息失败': ['Failure to obtain project information'],
    '请选择模板': ['Please select the TemplateSet'],
    '确定删除实例？': ['Sure to delete Instances'],
    '全选模板': ['Select all'],
    '清空全选': ['Clear selected'],
    '已经选择': ['Have chose'],
    '您没有可用的命名空间，请创建或申请已有命名空间使用': ['You do not have a namespace available. Create or apply for an existing namespace to use'],
    '创建或申请': ['Create or Apply'],
    '下存在': ['exist'],
    '类型的同名实例': ['same type instance'],
    '无法再次实例化': ['can not to be instantiate'],
    '的详细配置': ['Detailed configuration'],
    '确定要取消实例化操作？': ['Sure you to cancel the instantiation operation?'],
    '查看可用变量': ['View available variables'],
    '可用变量': ['Available variables'],
    '模板集中引入方式': ['TemplateSet include way'],
    '变量名': ['Variable Name'],
    '返回模板集': ['Return TemplateSets'],
    '30个以内的字符': ['Less than 30 characters'],
    '50个以内的字符': ['Less than 50 characters'],
    '您已经对此模板集加锁，只有解锁后，其他用户才可操作此模板集。': ['You have locked the TemplateSet, and only after unlocking can other users operate'],
    '当前版本号': ['Current version'],
    '点击刷新': ['Click to refresh'],
    '为避免多成员同时编辑，引起内容或版本冲突，建议在编辑时，开启保护功能。': ['In order to avoid editing at the same time and cause content or version conflict, it is suggested that lock when editing'],
    '保存草稿': ['Save Draft'],
    '无权限，请去': ['No permissions, please '],
    '申请': ['Apply'],
    '版本列表': ['Version List'],
    '保存修改到': ['Save to'],
    '新版本': ['New Version'],
    '请输入版本号': ['Please enter the version'],
    '其它版本': ['Other Version'],
    '请选择版本号': ['Please select the version'],
    '保存中...': ['Save...'],
    '版本号': ['Version'],
    '最后更新人': ['Updator'],
    '(当前)': ['(Current)'],
    '加载': ['Load'],
    '必须保留至少一个版本': ['At least one version must be retained'],
    '{locker}正在操作，您如需编辑请联系{locker}解锁！': ['{locker} in operation，If you need to edit, please contact {locker} to unlock'],
    '删除版本': ['Delete version'],
    '确定要删除此模板集？': ['Sure to delete this TemplateSet?'],
    '加锁成功': ['Lock success'],
    '解锁成功': ['Unlock successfully'],
    '保存成功': ['Save successfully'],
    '模板集基础信息保存成功': ['Information of TemplateSet has been saved successfully'],
    '模板集_': ['TemplateSet_'],
    '模板集描述': ['TemplateSet description'],
    '当前访问的模板集不存在': ['TemplateSet does not exist'],
    '请输入应用名称': ['Please enter application name'],
    '应用名称错误，只能包含：小写字母、数字、连字符(-)，必须是字母开头，长度小于30个字符': ['The application name is incorrect and can only contain: lowercase letters, numbers, hyphens (-), must be at the beginning of the letter, and the length is less than 30 characters'],
    '请输入实例数量': ['Please enter instances'],
    '网络模式的自定义值不能为空': ['Custom values ​​for network mode cannot be empty'],
    '容器名称': ['Container Name'],
    '名称不能为空': ['name is required'],
    '容器"{name}"的镜像及版本配置：请设置所属的镜像及版本': ['Container "{name}" image and version configuration：please set image and version'],
    '容器"{name}"的镜像及版本配置：原镜像已经删除，请重新选择': ['Container "{name}" image and version configuration：the original image has been deleted, please re-select'],
    '容器"{name}"的端口映射配置：名称不能为空': ['Container "{name}" port mapping configuration：name is required'],
    '容器"{name}"的端口映射配置：名称错误，以字母开头，只能含小写字母、数字、连字符(-)，首字母必须是字母，长度小于256个字符': ['Container "{name}" port mapping configuration：The name is wrong, starting with a letter, can only contain lowercase letters, numbers, hyphens (-), the first letter must be a letter, the length is less than 256 characters'],
    '添加': ['Add '],
    '未命名': ['Unnamed'],
    '导入JSON': ['Import JSON'],
    '导入': ['Import'],
    '名称必填，以字母开头，只能含小写字母、数字、连字符(-)': ['Name is required, beginning with a letter, can only contain lowercase letters, numbers, hyphens (-)'],
    '仓库获取': ['From Repo'],
    '添加Key': ['Add Key'],
    '值来源': ['Value source'],
    '在线编辑': ['Online Editing'],
    '请输入键': ['Please enter the key'],
    '的内容': [''],
    '请输入仓库中配置文件的相对路径': ['Please enter the relative path of the configuration file in the repository'],
    '实例化时会将值的内容做base64编码': ['The content of the value is base64 encoded when instantiated'],
    '键名错误，只能包含：字母、数字、连字符(-)、点(.)、下划线(_)，必须是字母开头，长度小于30个字符': ['The key name is incorrect and can only contain: letters, numbers, hyphens (-), dots (.), underscores (_), must be at the beginning of the letter, and the length is less than 30 characters'],
    '键不可重复': ['Key cannot be repeated'],
    '删除Secret': ['Delete Secret'],
    '为无效字段': [' is invalid field'],
    '请输入JSON': ['Please enter JSON'],
    '请输入合法的JSON': ['Please enter valid JSON'],
    '删除ConfigMap': ['Delete ConfigMap'],
    '关联': ['Associated'],
    '请先配置Application，再进行关联': ['Please configure Application first, then associate'],
    '升级策略': ['Upgrade strategy'],
    '请输入50个以内的字符': ['Please enter less than 50 characters'],
    '重新创建': ['Recreate'],
    '周期删除数': ['MaxUnavilable'],
    '决定了每个rolling周期内可以删除的taskgroup数量。如果原有的taskgroup已经全部删除，则后续每一次rolling中不会再删除taskgroup': ['Determines the number of taskgroups that can be deleted in each rolling cycle. If the original taskgroup has been deleted, the taskgroup will not be deleted in each subsequent rolling'],
    '周期新增数': ['MaxSurge'],
    '更新间隔': ['UpgradeDuration'],
    // '滚动顺序': ['RollingUpdate Order'],
    '先创建': ['Create First'],
    '先删除': ['Delete First'],
    '手动更新': ['Rolling Manually'],
    '输入': ['Enter'],
    // '是': ['True'],
    // '否': ['False'],
    '删除Deployment': ['Delete Deployment'],
    '删除DaemonSet': ['Delete DaemonSet'],
    '多个IP以逗号分隔': ['Multiple IPs separated by commas'],
    '请先配置关联应用的容器端口映射信息': ['Please configure the container port mapping information of the associated application first'],
    '删除Service': ['Delete Service'],
    '未保存': ['Unsaved'],
    '添加ConfigMap': ['Add ConfigMap'],
    '添加Application': ['Add Application'],
    '名称必填，只能包含：小写字母、数字、连字符(-)，必须是字母开头，长度小于30个字符': ['The name is required and can only contain: lowercase letters, numbers, hyphens (-), must be at the beginning of the letter, and the length is less than 30 characters'],
    '重要级别': ['Monitor Level'],
    '重要': ['important'],
    '一般': ['general'],
    '不重要': ['unimportant'],
    '请输入256个字符以内': ['Please enter within 256 characters'],
    '更多设置': ['More settings'],
    '容器异常退出后，自动重新调度': ['Automatically reschedule after the container exits abnormally'],
    '重启间隔步长': ['Restart Backoff'],
    '最多重启次数': ['Restart Maxtimes'],
    'Restart策略': ['Restart Policy'],
    'Kill策略': ['Kill Policy'],
    '宽期限': ['Grace Period'],
    '启用Metric数据采集': ['Enable Metric Data Collection'],
    'Metric数列（多选）': ['Metric List (multiple)'],
    '日志采集': ['Log Collection'],
    '标准日志': ['Standard Log'],
    '文件路径日志': ['File Path Log'],
    '系统日志': ['System Log'],
    '标准输出：包含容器Stdout日志': ['Standard output: Contains the container Stdout log'],
    '附加日志标签': ['Additional log label'],
    '附加的日志标签会以KV的形式追加到采集日志中': ['Additional log labels will appended to the collection log in the form of key-value'],
    '最多添加5个': ['Add up to 5'],
    '请输入30个字符以内': ['Please enter within 30 characters'],
    '总是在创建之前拉取镜像': ['Always pull the image before creating it'],
    '容器端口': ['Container Port'],
    '主机端口': ['Host Port'],
    '启动命令': ['Start Command'],
    '命令参数': ['Command Args'],
    '工作目录': ['Working Dir'],
    'Docker参数': ['Docker Parameter'],
    '挂载名': ['Volume Name'],
    '挂载源': ['Volume Source'],
    '容器目录': ['Container Dir'],
    '子路径': ['Sub Path'],
    '只读': ['Read'],
    '变量键': ['Variable Key'],
    '变量值': ['Variable Value'],
    '自定义类型可同时粘贴多行“键=值”的文本会自动添加多行记录': ['Custom type can paste multiple lines of "key=value" text at the same time will automatically add multi-line records'],
    '特权': ['Privilege'],
    '可完全访问母机资源': ['Full access to parent resources'],
    '核': ['Core'],
    '设置CPU requests，范围为0.001-128': ['Set CPU requests from 0.001 to 128'],
    '设置CPU limits，范围为0.001-128': ['Set CPU limits to a range of 0.001-128'],
    '设置CPU requests，1000m CPU=1核 CPU': ['Set CPU requests, 1000m CPU=1 core CPU'],
    '设置CPU limits，1000m CPU=1核 CPU': ['Set CPU limits, 1000m CPU=1 core CPU'],
    '设置内存limits': ['Set memory limits'],
    // '健康检查': ['Health Checks'],
    '请求路径': ['Request Path'],
    '请先配置完整的端口映射': ['Please configure the port mapping first'],
    '检查命令': ['Check Command'],
    '设置Header': ['Configure Header'],
    '高级设置': ['Advanced Settings'],
    '初始化超时': ['Initialization timeout'],
    '检查间隔': ['Check Interval'],
    '检查超时': ['Check Timeout'],
    '不健康阈值': ['Consecutive Failures'],
    '次失败': ['failed'],
    '次成功': ['success'],
    '健康检查连续失败的次数，达到次数后会重新调度容器': ['The number of consecutive failures of the health check. After the number of times, the container will be rescheduled'],
    '健康阈值': ['Grace Period Seconds'],
    '启动之后，该时间内的健康检查失败会被忽略': ['After the startup, the health check failure during this time will be ignored'],
    '非标准日志采集': ['Non-standard log'],
    '请输入容器中自定义采集的日志绝对路径': ['Please enter the absolute path of the log collected'],
    '镜像及版本': ['Image'],
    '无': ['None'],
    '自定义': ['Custom'],
    '不能修改协议': ['Cannot modify the agreement'],
    '容器名称不能为空！': ['Container name is required'],
    '容器名称错误，只能包含：小写字母、数字、连字符(-)，必须是字母开头，长度小于30个字符': ['The container name is incorrect and can only contain: lowercase letters, numbers, hyphens (-), must be at the beginning of the letter, and the length is less than 30 characters'],
    '容器{name}的镜像及版本配置：请设置所属的镜像及版本': ['Container {name} image and version configuration: please set the image and version'],
    '导入YAML': ['Import YAML'],
    '名称必填，以小写字母或数字开头和结尾，只能包含：小写字母、数字、连字符(-)、点(.)': ['The name is required, beginning and ending with a lowercase letter or number. It can only contain: lowercase letters, numbers, hyphens (-), dots (.)'],
    '键名错误，只能包含：字母、数字、连字符(-)、点(.)、下划线(_)，首字母必须是字母，长度小于30个字符': ['The key name is incorrect and can only contain: letters, numbers, hyphens (-), dots (.), underscores (_), the first letter must be a letter, and the length is less than 30 characters.'],
    '添加Secret': ['Add Secret'],
    '添加白名单': ['to Add whitelist'],
    'this': ['Note: the function is test, Please contact '],
    '请先配置Deployment，再进行关联': ['Please configure Deployment first, then associate'],
    '实例数范围': ['Instances range'],
    '最小': ['Min'],
    '最大': ['Max'],
    '扩缩容触发条件': ['Scale trigger condition'],
    '资源类型': ['Resource Type'],
    '资源目标': ['Resource Target'],
    '请选择资源类型': ['Please select a resource type'],
    '删除HPA': ['Delete HPA'],
    '{curHPA}中关联应用：关联的Deployment【{deploymentName}】不存在，请重新绑定！': ['{curHPA} associated app：Deployment【{deploymentName}】is not exist, please rebind！'],
    '添加Service': ['Add Service'],
    '请输入30个以内的字符': ['Please enter 30 characters or less'],
    '请先配置Deployment/DaemonSet/StatefulSet，再进行关联': ['Please configure Deployment/DaemonSet/StatefulSet first, then associate'],
    'Service使用标签来查找所有正在运行的容器。请注意：同一个命名空间下，使用了选中标签的应用都会被导流': ['Service uses tags to find all running containers. Please note: under the same namespace, applications that use the selected tag will be diverted'],
    '不填或None': ['Can empty or None'],
    '请输入ClusterIP': ['Please enter ClusterIP'],
    '输入node port值，值的范围为[30000-32767]；或者不填写，k8s会生成一个可用的随机端口，此时，可在 网络->Service 查看node port值': ['Enter the node port value, the range of values ​​is [30000-32767]; or leave it blank, k8s will generate a random port available. In this case, you can view the node port value in Network->Service.'],
    '请先填写已关联应用的容器端口映射信息': ['Please fill in the container port mapping information of the associated app first'],
    'ClusterIP为None时，端口映射可以不填；否则请先关联应用后，再填写端口映射': ['When the ClusterIP is None, the port mapping can be left blank. Otherwise, please associate the application before filling in the port mapping'],
    '查看示例': ['View example'],
    '"{name}"中关联应用：原已经关联的{type}已经删除，请重新选择': ['"{name}" associated application：The original {type} has been deleted, please re-select'],
    '请选择类型': ['Please choose the type'],
    '提示：K8S原生规则需在“网络” => “LoadBalancer”中新建LoadBalancer才能生效': ['Tip: K8S native rules need to create a new LoadBalancer in "Network" => "LoadBalancer" to take effect.'],
    '删除Ingress': ['Delete Ingress'],
    'TLS设置': ['TLS settings'],
    '主机名，多个用英文逗号分隔': ['Host name, separated by commas'],
    '选择一个证书': ['Choose a certificate'],
    '证书列表': ['Certificate list'],
    '添加Rule': ['Add Rule'],
    '主机名': ['Hostname'],
    '虚拟主机名': ['Hostname'],
    '路径组': ['Paths'],
    '{name}中路径组：关联的Service【{serviceName}】不存在，请重新绑定': ['{name} paths：Associate Service【{serviceName}】is not exist, please re-bind'],
    '关联的Service【{serviceName}】不存在，请重新绑定': ['Associate Service【{serviceName}】is not exist, please re-bind'],
    '服务名称': ['Service Name'],
    '添加Ingress': ['Add Ingress'],

    '请输入32个字符以内的名称': ['Please enter a name within 32 characters'],
    '添加Deployment': ['Add Deployment'],
    'k8S使用选择器(spec.selector.matchLabels)关联资源，实例化后选择器的值不可变': ['k8S use the selector (spec.selector.matchLabels) to associate resources, and the value of the selector is immutable after instantiation'],
    '小提示：K8S使用选择器（spec.selector.matchLabels）关联资源，必填，且实例化后选择器的值不可变': ['Tip: K8S use the selector (spec.selector.matchLabels) to associate resources, required, and the value of the selector after immutation is immutable'],
    'Pod模板设置': ['Pod template settings'],
    '更新策略': ['Update Strategy'],
    '亲和性约束': ['Affinity Constraint'],
    '启用': ['Enable'],
    '网络策略': ['Network Strategy'],
    'DNS策略': ['DNS Strategy'],
    '卷': ['Volumes'],
    '添加Container': ['Add Container'],
    '子目录': ['Subdirectory'],
    '请先在Pod模板设置中配置卷列表': ['Please configure the volume list in the Pod template settings first'],
    'ConfigMap列表': ['ConfigMap List'],
    'Secret列表': ['Secret List'],
    '设置CPU下限，1000m=1核CPU': ['Set CPU requests, 1000 m=1 core'],
    '设置CPU上限，1000m=1核CPU': ['Set CPU limits, 1000 m=1 core'],
    '设置内存下限': ['Set memory requests'],
    '设置内存上限': ['Set memory limits'],
    'Eg：/tmp/check.sh，多个命令用空格分隔': ['Eg:/tmp/check.sh, commands separated by spaces'],
    '就绪检查': ['Ready check'],
    'ConfigMap单键': ['ConfigMap Key'],
    'ConfigMap文件': ['ConfigMap File'],
    'Secret单键': ['Secret Key'],
    'Secret文件': ['Secret File'],
    '，不能修改协议': [', Can not modify the agreement!'],
    '标签 ({key}) 已经被Service ({value}) 关联，使用该标签的应用会被关联的Service导流': ['The tag ({key}) has been associated with Service ({value}), and the application that uses the tag is associated with the Service diversion'],
    '容器"{name}"的端口映射配置：端口名称不可重复': ['Port mapping configuration for container "{name}" : port names are not repeatable'],
    '容器"{name}"的端口映射配置：协议不能为空': ['Port mapping configuration for container "{name}" : the protocol cannot be empty'],
    '容器"{name}"的端口映射配置：容器端口不能为空': ['Port mapping configuration for container "{name}" : container port cannot be empty'],
    '容器"{name}"的端口映射配置：容器端口范围为1-65535': ['Port mapping configuration for container "{name}" : container port range 1-65535'],
    '容器"{name}"的端口映射配置：主机端口不能为空': ['Port mapping configuration for container "{name}" : host port cannot be empty'],
    '容器"{name}"的端口映射配置：主机端口范围为0-65535': ['Port mapping configuration for container "{name}" : host port range 0-65535'],
    '容器"{name}"的命令：启动命令不能含有中文字符': ['Container "{name}" command: the startup command cannot contain Chinese characters'],
    '容器"{name}"的命令：命令参数不能含有中文字符': ['Container "{name}" command: command arguments cannot contain Chinese characters'],
    '容器"{name}"的挂载卷配置：挂载名不能为空': ['Mount volume configuration for container "{name}" : mount name cannot be empty'],
    '容器"{name}"的挂载卷配置：挂载名错误，只能包含：字母、数字、连字符(-)、下划线(_)，首字母必须是字母，长度小于30个字符': ['Mount volume configuration for container "{name}" : mount name error, can only contain: letter, number, hyphen (-), underscore (_), first letter must be letter, length less than 30 characters'],
    '容器"{name}"的挂载卷配置：挂载源不能为空': ['Mount volume configuration for container "{name}" : mount source cannot be empty'],
    '容器"{name}"的挂载卷配置：容器目录不能为空': ['Mount volume configuration for container "{name}" : the container directory cannot be empty'],
    '容器"{name}"的挂载卷配置：容器目录不正确': ['Mount volume configuration for container "{name}" : incorrect container directory'],
    '容器"{name}"的环境变量配置：键不能为空': ['Environment variable configuration for container "{name}" : the key cannot be empty'],
    '容器"{name}"的环境变量配置：值不能为空': ['Environment variable configuration for container "{name}" : the value cannot be empty'],
    '容器"{name}"的资源限制配置：CPU和内存限制必须配置': ['Resource limit configuration for container "{name}" : CPU and memory limits must be configured'],
    '容器"{name}"的资源限制配置：CPU上限不能少于0.001': ['Resource limit configuration for container "{name}" : CPU limits cannot be less than 0.001'],
    '容器"{name}"的资源限制配置：CPU上限不能大于128': ['Resource limit configuration for container "{name}" : CPU limits cannot be greater than 128'],
    '容器"{name}"的资源限制配置：内存上限不能为空': ['Resource limit configuration for container "{name}" : memory limits cannot be empty'],
    '容器"{name}"的资源限制配置：CPU上限不能小于下限': ['Resource limit configuration for container "{name}" : CPU requests cannot be less than the requests'],
    '容器"{name}"的资源限制配置：CPU下限不能少于0.001': ['Resource limit configuration for container "{name}" : CPU requests cannot be less than 0.001'],
    '容器"{name}"的资源限制配置：CPU下限不能大于128': ['Resource limit configuration for container "{name}" : CPU requests cannot be greater than 128'],
    '容器"{name}"的资源限制配置：CPU上限不能为空': ['Resource limit configuration for container "{name}" : CPU limits cannot be empty'],
    '容器"{name}"的资源限制配置：内存上限不能小于下限': ['Resource limit configuration for container "{name}" : memory limits cannot be less than the requests'],
    '容器"{name}"的资源限制配置：CPU下限不能为空': ['Resource limit configuration for container "{name}" : CPU requests cannot be empty'],
    // '容器"{name}"的资源限制配置：内存上限不能小于下限': ['Resource limit configuration for container "{name}" : memory limits cannot be less than the requests'],
    '容器"{name}"的健康检查配置：端口名称不能为空': ['Health check configuration for container "{name}" : port name cannot be empty'],
    '容器"{name}"的健康检查配置：检查命令不能为空': ['Health check configuration for container "{name}" : check command cannot be empty'],
    '容器"{name}"的非标准日志采集配置：日志绝对路径不正确': ['Non-standard log collection configuration for container "{name}" : the log absolute path is incorrect'],
    '请填写1至45个字符（由字母、数字、下划线以及 - 或 . 组成）': ['Please fill in 1 to 45 characters (composed of letters, Numbers, underscores and - or.)'],
    '版本{versionKeyword}已经存在': ['Version {versionKeyword} already exists'],
    '中': [': '],
    '关联：': ['Associated: '],
    '关联应用：': ['Associated application: '],
    '实例数范围：': ['Instance range: '],
    '最小实例数不能为空': ['The min number of instances cannot be empty'],
    '最大实例数不能为空': ['The max number of instances cannot be empty'],
    '最大实例数不能小于最小实例数': ['The max number of instances cannot be less than the min'],
    '扩缩容触发条件：': ['Scale trigger conditions: '],
    '资源目标不能为空': ['Resource targets cannot be empty'],
    '此操作存在风险': ['This operation is danger'],
    '此操作存在风险，请知悉': ['Please note that this operation is danger'],
    'k8s内部使用 spec.selector.matchLabels 关联资源, 直接修改 matchLabel 会导致产生某些“孤儿”资源 （例如修改没有Deployment管理的 ReplicaSet）': ['K8s used within the spec.selector.matchLabels associated resources, directly modify matchLabel can lead to some "orphan" resources (such as modified no Deployment management ReplicaSet)'],
    '应用名称错误，以小写字母或数字开头和结尾，只能包含：小写字母、数字、连字符(-)、点(.)': ['Application name error, starting and ending with lowercase letters or Numbers, can only contain: lowercase letters, Numbers, hyphens (-), dots (.)'],
    '名称错误，以小写字母或数字开头和结尾，只能包含：小写字母、数字、连字符(-)、点(.)': ['Name error, starting and ending with lowercase letters or Numbers, can only contain: lowercase letters, Numbers, hyphens (-), dots (.)'],
    'key值只能包含数字、字母、中划线(-)、下划线(_)、点(.)、斜杆(/)，开头结尾必须是数字或字母': ['Application name error, starting and ending with lowercase letters or Numbers, can only contain: lowercase letters, Numbers, hyphens (-), dots (.)'],
    '必须添加一个选择器': ['A selector must be added'],
    '卷模板': ['Volume template'],
    '挂载名只能含数字、字母、中划线(-)、下划线(_)、点(.)，开头结尾必须是数字或字母': ['Mount names can only contain Numbers, letters, underscores (-), underscores (_), dots (.), and must begin and end with Numbers or letters'],
    '请选择StorageClassName': ['Please select StorageClassName'],
    '请设置大小': ['Please set the size'],
    '请选择访问模式': ['Please select access mode'],
    '挂载名不能为空': ['The mount name cannot be empty'],
    '挂载源不能为空': ['The mount source cannot be empty'],
    '挂载名只能包含：字母、数字、连字符(-)，首字母必须是字母，长度小于253个字符': ['The mount name can only contain: letter, number, hyphen (-), the first letter must be a letter, length less than 253 characters'],
    '亲和性约束格式不正确': ['The affinity constraint is incorrectly formatted'],
    '名称错误，只能包含：小写字母、数字、连字符(-)，首字母必须是字母，长度小于30个字符': ['Wrong name, can only contain: lowercase, numeric, hyphen (-), the first letter must be a letter, length less than 30 characters'],
    '容器"{name}"的端口映射配置：名称错误，以小写字母开头，只能包含：小写字母、数字、连字符(-)，长度小于256个字符': ['Port mapping configuration for container "{name}" : misnamed, starts with a lowercase letter, can contain only: lowercase letter, number, hyphen (-), length less than 256 characters'],
    '容器"${name}"的挂载卷配置：挂载名不能为空': ['Mount volume configuration for container "${name}" : mount name cannot be empty'],
    '容器"{name}"的环境变量配置：键只能含数字、字母、中划线(-)、下划线(_)、点(.)，开头结尾必须是数字或字母': ['Environment variable configuration for container "{name}" : keys can only contain Numbers, letters, underscore (-), underscore (_), dot (.), and must begin or end with a number or letter'],
    '容器"{name}"的资源限制配置：CPU限制中最小值必须小于等于最大值': ['Resource limit configuration for container "{name}" : the min CPU limit must be less than or equal to the max'],
    '容器"{name}"的资源限制配置：内存限制中最小值必须小于等于最大值': ['Resource limit configuration for container "{name}" : the min value in the memory limit must be less than or equal to the max'],
    '容器"{name}"的生命周期：停止前执行不能含有中文字符': ['Container "{name}" life cycle: execution cannot contain Chinese characters before stopping'],
    '容器"{name}"的生命周期：启动后执行不能含有中文字符': ['Container "{name}" life cycle: execution after startup cannot contain Chinese characters'],
    '必须添加至少一个Container类型的容器': ['You must add at least one of type Container'],
    '规则': ['Rules'],
    '主机名不能为空': ['The host name cannot be empty'],
    '规则主机名': ['Rule host name'],
    '路径不正确': ['incorrect path'],
    '请关联服务端口': ['Please associate the service port'],
    '不可同时绑定多个StatefulSet': ['Multiple statefulsets cannot be bound at the same time'],
    '请选择要关联的标签': ['Please select the label to associate with'],
    '请输入正确IP地址或“None”值': ['Please enter the correct IP address or "None" value'],
    '请先添加键': ['Please add the key first'],
    '添加DaemonSet': ['Add DaemonSet'],
    '多个命令用空格分隔': ['commands are separated by Spaces'],
    '多个参数用空格分隔': ['parameters are separated by Spaces'],
    '设置内存requests': ['Set memory requests'],
    '启动后执行': ['Post-start exec'],
    '停止前执行': ['Pre-stop exec'],
    '标签 ({key}) 已经被Service ({service}) 关联，使用该标签的应用会被关联的Service导流': ['The tag ({key}) has been associated with the Service ({Service}), and the application using the tag will be channeled'],
    '添加Job': ['Add Job'],
    '删除Job': ['Delete Job'],
    '添加StatefulSet': ['Add StatefulSet'],
    '删除StatefulSet': ['Delete StatefulSet'],
    '联系我们': ['Contact Us'],
    '添加至选择器': ['Add to selector'],
    '生命周期': ['Life cycle'],
    'Pod运行设置': ['Pod runtime setting'],
    'Pod管理策略': ['Pod manage strategy'],
    'K8S原生': ['K8S'],
    '注意：功能灰度测试中，请联系': ['Note: Please contact us in the function test'],
    '添加HPA': ['Add HPA'],
    '操作者': ['Operator'],
    '请选择要删除的Service': ['Please choose the Service to delete'],
    '删除Namespace成功': ['Delete namespace successfully'],
    '共': [''],
    '个模板集': ['TemplateSet'],

    '变量管理': ['Variables'],
    '新增变量': ['Add Variable'],
    '变量名称': ['Variable Name'],
    '默认值': ['Defaults'],
    '作用范围': ['Scope'],
    '引用处': ['Reference'],
    '批量更新': ['Batch Update'],
    '系统内置变量，不能编辑': ['System variables, can not edit'],
    '系统内置变量': ['System Variable'],
    '已经被引用，不能删除': ['Already referenced, cannot be deleted'],
    '所属': ['Belong'],
    '确定要删除以下变量？': ['Sure to delete this Variable?'],
    '全局变量': ['Global Variable'],
    '命名空间变量': ['Namespace Variable'],
    '说明': ['Description'],
    '提交': ['Submit'],
    '被引用位置': ['Referenced'],
    '上下文': ['Context'],
    '全部作用范围': ['All Scopes'],
    '编辑变量': ['Edit Variable'],
    '请选择要删除的变量': ['Please select the Variable to delete'],
    '确定要删除变量': ['Sure to delete this Variable'],
    '请输入变量名称': ['Please Input the Variable name'],
    '请输入32个字符以内的变量名称': ['Please enter a variable name within 32 characters'],
    '请输入变量KEY': ['Please input the Variable key'],
    'KEY 只能包含字母、数字和下划线，且以字母开头，最大长度为64个字符': ['KEY can only contain letters, numbers, and underscores, starting with a letter and having a maximum length of 64 characters'],
    '变量创建成功': ['Variable created successfully'],
    '变量更新成功': ['Variable update succeeded'],
    '变量删除成功': ['Variable delete succeeded'],
    '集群IP': ['Cluster IP'],
    '您可以在模板集中使用': ['you can use'],
    '来引用该变量': ['to import this Variable'],
    '变量KEY': ['Variable Key'],
    '模板实例化操作即平台通过用户配置的模板，生成对应的资源json文件，并将它们下发到指定集群的命名空间下。资源创建成功后，可在"应用"和"网络"中查看资源实例详情。': ['Template instantiation means that the platform generates the corresponding resource json files through the user-configured templates and sends them to the namespace of the specified cluster. After the resource is created successfully, you can view the resource instance details in Application and Network.'],
    '模板实例化操作即平台通过用户配置的模板，生成对应的资源YAML文件，并将它们下发到指定集群的命名空间下。资源创建成功后，可在"应用"和"网络"中查看资源实例详情。': ['Template instantiation means that the platform generates the corresponding resource YAML files through the user-configured templates and sends them to the namespace of the specified cluster. After the resource is created successfully, you can view the resource instance details in Application and Network.'],
    '命名空间：YAML模板集命名空间在实例化时生效，在编辑YAML文件时不需要填写（会在保存时被置为占位符）': ['Namespace: The YAML TemplateSet namespace takes effect when instantiated, and does not need to be filled in when editing YAML files (it will be set as a placeholder when saving)'],
    // '请输入名称': ['please enter name'],
    'HPA是Mesos自动扩缩容服务，利用HPA能够根据监测到 cpu、memory 的利用率': ['HPA is Mesos automatic expansion and contraction service, which can monitor the utilization of cpu and memory based on HPA.'],
    'Service主要用于服务发现、DNS基础数据、loadbalance服务导出': ['Service is mainly used for service discovery, DNS basic data, and loadbalance service export'],
    '详情查看文档': ['See the documentation for details'],
    'Secret是一种包含少量敏感信息例如密码、token 或 key 的对象，与ConfigMap相比更加安全': ['Secret is an object that contains a small amount of sensitive information such as passwords, tokens, or keys, and is more secure than ConfigMap'],
    'ConfigMap是用来存储配置文件的Mesos资源对象，它的作用是将配置文件从容器镜像中解耦，从而增强容器应用的可移植性': ['ConfigMap is a Mesos resource object used to store configuration files. Its purpose is to decouple the configuration files from the container image to enhance the portability of the container application'],
    'Deployment是基于bcs-application抽象出的顶层概念，主要满足应用的滚动升级、回滚、暂停、扩缩容等需求': ['Deployment is based on the top-level concept abstracted by bcs-application, which mainly meets the requirements of rolling upgrade, rollback, pause, expansion and contraction of applications'],
    'Application实现Pod的含义，并与k8s的RC，Mesos的app概念等价': ['Application implements the meaning of Pod and is equivalent to the concept of k8s RC, Mesos app'],
    'ConfigMap是用来存储配置文件的k8s资源对象，它的作用是将配置文件从容器镜像中解耦，从而增强容器应用的可移植性': ['ConfigMap is a k8s resource object used to store configuration files. Its purpose is to decouple the configuration files from the container image to enhance the portability of the container application'],
    'DaemonSet能够让所有（或一些特定）的Node节点运行同一个Pod。新加入集群的节点上会新增该Pod；节点被移除时，Pod也会被销毁': ['DaemonSet enables all (or some specific) Node nodes to run the same Pod. The Pod will be added to the node newly added to the cluster; when the node is removed, the Pod will also be destroyed'],
    'Deployment是k8s中标准的无状态服务，集成了上线部署、滚动升级、创建副本、回滚等功能': ['Deployment is a standard stateless service in k8s, integrating on-line deployment, rolling upgrade, creating replicas, rolling back, etc'],
    'HPA (Horizontal Pod Autoscaler) 是k8s自动扩缩容服务，利用HPA，k8s能够根据监测到的 cpu, memory 利用率, 自动的扩缩容 Deployment 中 Pod 的数量': ['HPA (Horizontal Pod Autoscaler) is a k8s automatic expansion and contraction service. With HPA, k8s can automatically expand and shrink the number of Pods in the deployment based on the monitored cpu and memory utilization'],
    'Ingress是管理外部访问集群内服务的对象，可配置访问的URL、基于名称的虚拟主机等。 Ingress controller负责实现Ingress，BCS使用的是nginx-controller': ['Ingress is an object that manages external access to services within a cluster. It can be configured with URLs for access, name-based virtual hosts, and so on. The Ingress controller is responsible for implementing Ingress, and the BCS is using nginx-controller'],
    'Job负责批量处理短暂的一次性任务，即仅执行一次的任务，它保证批处理任务的一个或多个Pod成功结束': ['Job is responsible for batch processing of short-lived one-time tasks, that is, tasks that are executed only once, which guarantees that one or more Pods of the batch task end successfully'],
    'Service从逻辑上定义了运行在集群中的一组Pod，通常通过selector绑定，将Pod服务公开访问': ['Service logically defines a set of Pods running in the cluster, usually through the selector binding, public access to the Pod service'],
    'StatefulSet是k8s中标准的有状态服务，区别于Deployment，它是一个给Pod提供唯一标志的控制器，可以保证部署和扩展的顺序': ['StatefulSet is a standard stateful service in k8s. It is different from Deployment. It is a controller that provides a unique identifier for Pod. It can guarantee the order of deployment and expansion'],
    '同步命名空间': ['Sync Namespaces'],
    '同步非本页面创建的命名空间数据': ['Sync namespaces not created from this page'],
    '同步命名空间任务已经启动，请稍后刷新': ['The sync namespaces task has started, please refresh later'],
    '类型': ['Type'],
    '导出': ['Export'],
    'YAML中资源所属的命名空间不需要用户指定，由平台根据用户实例化时的选择自动生成': ['Namespace does not need to be specified by the user, and is automatically generated by the platform according to the selection of the user when instantiating'],
    '返回编辑': ['Return to edit'],
    '修改对比': ['Modify comparison'],
    '变量列表': ['Variable list'],
    '镜像查询': ['Images query'],
    '请选择需要编辑的资源文件': ['Please select the resource file you want to edit'],
    '选择镜像': ['Choose image'],
    '使用指南：请将镜像复制后填入所使用的YAML中': ['Usage Guide: Please copy the image and fill it in the YAML used'],
    '新建版本': ['New version'],
    '{{变量KEY}}': ['{{Variable Key}}'],
    '模板编辑的内容未保存，确认要离开？': ['The content edited has not been saved. Sure you want to leave?'],
    '请输入资源文件名称': ['Please enter the resource file name'],
    '文件名称错误，只能包含：小写字母、数字、点(.)、连字符(-)，必须是字母开头，长度小于64个字符': ['The file name is incorrect and can only contain: lowercase letters, numbers, dots (.), hyphens (-), must be at the beginning of the letter, and the length is less than 64 characters'],
    '文件名称不能重复': ['File name cannot be repeated'],
    '请输入模板集名称': ['Please enter a TemplateSet name'],
    '请输入模板集描述': ['Please enter a TemplateSet description'],
    '请输入资源文件内容': ['Please enter the resource file content'],

    '输入名称或命名空间，按Enter搜索': ['Enter keyword and press Enter'],
    '明文显示': ['show'],
    '隐藏': ['hide'],
    '确定要删除ConfigMap': ['Sure to delete this ConfigMap'],
    '确定要删除以下ConfigMap？': ['Sure to delete this ConfigMap?'],
    '请选择要删除的ConfigMap': ['Please select the ConfigMap to delete'],
    '更新成功': ['update completed'],
    '确定要删除以下Secret？': ['Sure to delete this Secret?'],
    '请选择要删除的Secret': ['Please select the Secret to delete'],
    '确定要删除Secret': ['Sure to delete this Secret'],
    '已选择{remainCount}个节点': ['{remainCount} items'],
    '点击查看原因': ['Click to view the reason'],
    '请注意：命名空间{name}下的同名资源将会被覆盖更新，确认创建？': ['Please note: the resource with the same name under the namespace {name} will be overwritten and updated to confirm the creation?'],
    '表单模式': ['Form Mode'],
    '提示：容器端口是容器内部的Port。在配置Service的端口映射时，通过"目标端口"进行关联，从而暴露服务': ['Tip: The container port is the port inside the container. When configuring the port mapping of the Service, the association is made through the "target port" to expose the service'],
    '提示：项目镜像不存在，': ['Tip: The project image does not exist,'],
    '去创建': ['To create'],
    '管理Metric': ['Manage Metric'],
    '更新过程中能够进入不可用状态的 Pod 的最大个数': ['The maximum number of Pods that can enter the unavailable state during the update process'],
    '更新过程中能够额外创建的 Pod 的最大个数': ['The maximum number of Pods that can be additionally created during the update process'],
    '刷新镜像列表': ['Refresh images'],
    '请先在"Pod模板设置" -> "卷"中设置': ['Please set it in "Pod Template Settings" -> "Volumes" first'],
    '引用端口映射中的端口设置': ['Refer to the port settings in the port map'],
    '端口映射示例': ['Port mapping example'],
    '应用Container': ['Application Container'],
    '用于在启动应用Container之前，启动一个或多个“初始化”容器，完成应用Container所需的预置条件': ['Used to start one or more "initialize" containers and complete the pre-conditions required to apply the container before launching the application container'],
    '提示：同一个虚拟主机名可以有多个路径': ['Tip: The same virtual hostname can have multiple paths'],
    '暂无数据': ['No data'],
    '无匹配数据': ['No matching data'],

    '容器服务未启用': ['Container service is not enabled'],
    '，请完善以下信息': [', complete information'],
    '业务编排类型': ['Orchestration Engine'],
    '当前账号无有权限的业务，请到': ['If the current account has no permission, please go to '],
    '权限中心': ['authority center '],
    '申请，': ['apply, '],
    '查看帮助': ['view help'],
    '您当前的项目': ['Your current project '],
    '资源': ['Resource'],
    '需要的权限': ['Required permissions'],
    '去申请': ['Apply'],
    '无权限操作': ['No permission operation'],
    '新建证书': ['New certificate'],
    '编辑证书': ['Edit certificate'],
    '请输入名称，英文大小写、数字、下划线和英文句号，最大长度为64个字符': ['Please enter a name, English case, number, underscore and period, the maximum length is 64 characters'],
    '请输入证书': ['Please enter a certificate'],
    '请输入私钥': ['Please enter the private key'],
    '确认要删除证书': ['Sure to delete the certificate'],
    '请输入Name': ['Please enter Name'],
    'Name错误，只能包含英文大小写、数字、下划线和英文句号': ['Name error, can only contain English capitalization, numbers, underscores and periods'],
    '请输入Cert': ['Please enter Cert'],
    '请输入Key': ['Please enter Key'],
    '更新证书成功': ['Update certificate successfully'],
    '创建证书成功': ['Successful certificate creation'],
    '同步仓库中的Helm Chart': ['Sync Helm Chart'],
    '通过Helm Chart、Client、模板集YAML模式创建的应用，请通过命名空间视图查询详情': ['For applications created by Helm Chart, Client, and YAML mode TemplateSet, please query the details through the namespace view'],
    '展示通过模板集表单模式实例化的应用详情': ['Show application details instantiated through TemplateSet form mode'],
    '共包含': ['Include'],
    '个应用模板': ['templates'],
    '展示通过命名空间页面创建的命名空间的应用详情': ['Show application details for namespaces created through namespace pages'],
    'Sorry，您的权限不足！': ['Sorry, your permissions are not enough!'],
    '页面找不到了！': ['The page could not be found!'],
    '服务器维护中，请稍后重试!': ['In server maintenance, please try again later!'],
    '功能正在建设中···': ['The function is under construction···'],
    '请确认以上内容，才可操作': ['Please confirm the above to operate'],
    '查看引用': ['View References'],
    '添加卷': ['Add Volume'],
    '添加挂载卷': ['Add Mounted volume'],
    '启用容器服务': ['Enable BCS'],
    '50个以内的字符，Enter保存': ['50 characters or less, Enter to save'],
    '30个以内的字符，Enter保存': ['30 characters or less, Enter to save'],
    '当前版本': ['Current Version'],
    '请通过模板集创建Service': ['Please create a Service through a TemplateSet'],
    '请通过模板集或Helm创建Service': ['Please create a Service through a TemplateSet or Helm'],
    '请通过模板集创建ConfigMap': ['Please create a ConfigMap through a TemplateSet'],
    '请通过模板集或Helm创建ConfigMap': ['Please create a ConfigMap through a TemplateSet or Helm'],
    '请通过模板集创建Ingress': ['Please create a Ingress through a TemplateSet'],
    '请通过模板集或Helm创建Ingress': ['Please create a Ingress through a TemplateSet or Helm'],
    '请通过模板集创建Secret': ['Please create a Secret through a TemplateSet'],
    '请通过模板集或Helm创建Secret': ['Please create a Secret through a TemplateSet or Helm'],

    '所属集群/命名空间': ['Cluster/Namespace'],
    '更新/创建时间': ['Update/Create Time'],
    '访问方式': ['Access'],
    '其他信息': ['Other Info'],
    '集群内访问': ['Access Internal'],
    '集群外访问': ['Access External'],
    'CL5路由': ['CL5 Router'],
    '新建CL5': ['Create CL5'],
    '业务模块': ['Business Module'],
    '责任人': ['Responsible Person'],
    '请输入业务模块': ['Please Enter Business Module'],
    '当前功能在灰度中，请联系容器助手下发CL5 controller才能生效': ['Please contact BCS assistant to take effect.'],
    '请填写业务模块': ['Please Enter Business Module'],
    'Node节点所属的CMDB三级业务模块ID': ['CMDB Level 3 Business Module ID to which the Node belongs'],
    '入流量': ['Network Receive'],
    '出流量': ['Network Transmit'],
    'Values文件：': ['Values File：'],
    '磁盘写数据': ['Disk Write'],
    '磁盘读数据': ['Disk Read'],
    '磁盘IO总量': ['DiskIO Total'],
    '阈值': ['Threshold'],
    '网络使用率': ['Network Usage'],
    'IO使用率': ['IO Usage'],
    '添加 HostAlias': ['Add HostAlias'],
    '请输入，多个HostName以英文分号(;)分隔': ['Please enter multiple hostNames separated by semicolons (;)'],
    '请输入合法IP地址': ['Please enter a valid IP address'],
    'IP不能为空': ['IP cannot be empty'],
    'HostNames不能为空': ['HostNames cannot be empty'],
    '新建CloudLoadBalancer': ['New CloudLoadBalancer'],
    '区域': ['Region'],
    '服务发现机制': ['Service find strategy'],
    '回滚上一版本': ['Rollback previous version'],
    '当前版本配置': ['Current Config'],
    '上一版本配置': ['Previous Config'],
    '{instanceName}回滚上一版本': ['{instanceName} rollback previous version'],
    '确定回滚上一版本【{instanceName}】？': ['Confirm to rollback previous version [{instanceName}]?'],
    '回滚中...': ['Rollbacking'],
    '监听器详情': ['Listener details'],
    '监听端口': ['Listener Port'],
    '健康状态': ['Health Status'],
    '集群版本': ['Cluster Version'],
    'Pod总量': ['Total Pod'],
    'Service数量上限/集群': ['Maximum number of services'],
    'Pod数量上限/节点': ['Number of Pods per node'],
    '重新添加': ['ReInstall'],
    '所选节点均处于初始化失败状态时才允许此操作': ['Allow this operation only if the selected nodes are in an initialization failure state'],

    '规则"{name}"的Service名称：请选择Service名称': ['Service name for rule "{name}": Please select a service name'],
    '规则"{name}"的协议：请选择协议': ['Protocol for rule "{name}": Please select a protocol'],
    '规则"{name}"的端口：请选择端口': ['Port for rule "{name}": Please select a port'],
    '规则"{name}"的会话保持时间：会话保持时间范围为30-3600': ['Session hold time for rule "{name}": Session hold time range is 30-3600'],
    '规则"{name}"的会话保持时间：请输入会话保持时间': ['Session hold time for rule "{name}": Please enter a session hold time'],
    '规则"{name}"的监听CLB端口：请输入监听CLB端口': ['CLB port for rule "{name}": Please enter CLB port for listening'],
    '规则"{name}"的开启Https：如果认证模式为mutual，客户端证书ID为必填项': ['Enable Https for rule "{name}": if the authentication mode is mutual, the client certificate is required'],
    '负载均衡策略': ['Load balancer strategy'],
    '健康检查策略': ['Health check strategy'],
    '已启用': ['activated'],
    '未启用': ['Not activated'],
    '添加规则': ['Add Rule'],
    '监听CLB端口': ['CLB Port'],
    '会话保持时间': ['Session Hold Time'],
    '响应超时时间': ['Response Timeout'],
    '探测间隔时间': ['Detection Interval'],
    '探测路径': ['Detection Path'],
    '健康状态码': ['Health Status Code'],
    '开启Https': ['Use Https'],
    '认证模式': ['Authentication Mode'],
    '证书ID': ['Certificate ID'],
    '不可删除': ['Cannot be delete'],
    'Kubernetes官方维护的Ingress Controller': ['Kubernetes Officially Maintained Ingress Controller'],
    'K8S官方维护的ingress-nginx': ['K8S officially maintained ingress-nginx'],
    '请选择CLB': ['Please select CLB'],
    '请选择区域': ['Please select a region'],
    '客户端证书ID': ['CertCaId'],
    '客户端证书的 ID，如果 mode=mutual，监听器如果不填写此项则必须上传客户端证书，包括 certClientCaName，certCilentCaContent': ['CertCaId. If mode = mutual, the listener must upload the client certificate if it is not filled in, including certClientCaName, certCilentCaContent'],

    '访问权限': ['Access Mode'],
    '回收策略': ['Reclaim Policy'],
    '云盘类型': ['Cloud Type'],
    '计费模式': ['Billing'],
    '升级': ['Upgrade'],
    '确定要升级新版本': ['Confirm to Upgrade'],
    '升级大约需要 1~2 分钟，请勿重复提交；升级过程中 Prometheus 服务将会重启，数据无损失': ['Upgrade takes about 1 to 2 minutes and do not repeat submissions; Prometheus service will be restarted without losses'],

    '按上面的模板创建你的json文件，选择“文件导入”操作': ['Create your json file according to the above template, select "file import" operation'],
    'scope值含义，global表示全局变量，cluster表示集群变量，namespace表示命名空间变量': ['The meaning of scope value, global means global variable, cluster means cluster variable, and namespace means namespace variable'],
    'cluster和namespace变量需要提供vars关键字，cluster变量的vars需要包含集群ID cluster_id和变量值 value': ['The cluster and namespace variables need to provide the vars keyword, and the vars of the cluster variable need to contain the cluster ID cluster_id and the variable value'],
    'namespace变量的vars需要包含集群ID cluster_id、命名空间名称 namespace 和变量值 value': ['The vars of the namespace variable need to contain the cluster ID cluster_id, the namespace name namespace and the variable value'],
    '如何从文件导入变量？': ['How to import variables from a file?'],
    '批量导入成功': ['Batch import succeeded'],
    '命名空间包含以下资源，请先删除资源，然后再删除命名空间': ['The namespace contains the following resources. Please delete the resource before deleting the namespace'],
    '无数据（请检查 Service 是否有关联的 Endpoints)': ['No data (please check whether Service has an associated Endpoints)'],
    '无数据（新建 Metric 需要1~2分钟生效，请刷新），通过计算创建时间和当前时间判断': ['No data (it takes 1 / 2 minutes for the new Metric to take effect, please refresh it), which can be judged by calculating the creation time and the current time.'],
    '集群分类': ['Cluster Category'],
    '新建集群': ['Create Cluster'],
    '导入集群': ['Import Cluster'],
    '导入已经存在的集群': ['Import an existing cluster'],
    '剩余': ['Surplus'],
    '容器视图': ['ContainerView'],
    'Taskgroup视图': ['TaskgroupView'],
    'POD视图': ['PODView'],
    '请输入64个字符以内': ['Please enter within 64 characters'],
    '只允许导入从已有模板集导出的zip包': ['Only zip packages exported from an existing template set are allowed to be imported'],
    'Values文件命名规范是以values.yaml结尾，例如xxx-values.yaml': ['The values file naming convention is based on values.yaml End, e.g. XXX- values.yaml'],
    '选择要删除的版本': ['Select version to delete'],
    '您需要先删除所有Release，再进行Chart删除操作': ['You need to delete all releases before deleting chart'],
    '删除Chart': ['Delete Chart'],
    '例如/bin/bash': ['例如/bin/bash'],
    '多个参数用空格分隔，例如"-c"  "while true; do echo hello; sleep 10;done"': ['Multiple parameters are separated by spaces, eg: "- C" "while true; do echo hello; sleep 10; done"'],
    '多个命令用空格分隔，例如/bin/bash "-c"  "while true; do echo hello; sleep 10;done"': ['Multiple commands are separated by spaces, Eg:/bin/bash "-c" "while true; do echo hello; sleep 10; done"'],
    '多个命令用空格分隔，例如/bin/bash &quot;-c&quot;  &quot;while true; do echo hello; sleep 10;done&quot;': ['Multiple commands are separated by spaces, eg: / bin / bash &amp; quote; - C &amp; quote; &amp; quote; while true; do echo hello; sleep 10; done &amp; quote;'],
    'Metric参数': ['Metric Params'],
    '请填写参数名称': ['Please enter params name'],
    '请填写参数值': ['Please enter params value'],
    '集群升级': ['Cluster Upgrade'],
    '升级过程需要业务停机；升级完后暂不支持版本回退': ['Upgrade process requires business downtime; Version fallback is not supported after the upgrade.'],
    '当前集群暂无可用的升级版本': ['There is no upgrade version available for the current cluster'],
    '集群升级成功': ['Cluster Upgrade Success'],
    '正在升级中，请稍等···': ['Upgrading'],
    '升级失败，请重试': ['InitialUpgradeization failed, please try again'],
    '重新升级': ['Reupgrade'],
    '确定重新升级？': ['Are you sure you want to reupgrade?'],
    '请确认以下配置：': ['Please confirm the following configuration: '],
    '集群仅允许创建{x}个节点，{y}个service，每个节点{z}个pod，创建后，不允许调整': ['The cluster is only allowed to create {x} nodes, {y} service, each node has {z} pod, after creation, adjustment is not allowed'],
    '请选择集群版本': ['Please Select Cluster Version'],
    '文件名称': ['File Name'],
    '名称不能重复': ['The name cannot be repeated'],
    '文件': ['File'],
    '目录': ['Catalog'],
    '重命名': ['Rename'],
    '新增文件': ['Add File'],
    '新增目录': ['Add Catalog'],
    '导入模板集': ['Import Templateset'],
    '新建CL5成功': ['Create CL5 Success'],
    '是否有sid': ['has sid'],
    '转换到YAML': ['Export To YAML'],
    '选择Service以获取Label': ['Select Service for get Label'],
    '服务器来源：': ['Host Source: '],
    '平台资源池': ['BIZ Host'],
    '业务资源池': ['BCS Host'],
    'Pod数量': ['Pods'],
    '调度引擎': ['COES'],
    '输入集群名称搜索': ['Enter Cluster to Search'],
    '输入命名空间搜索': ['Enter Namespace to Search'],
    '请选择CRD': ['Please Select CRD'],
    '输入CRD搜索': ['Enter CRD to Search'],
    '输入名称搜索': ['Enter Name to Search'],
    'IP数量(个)': ['IPs'],
    '可用IP(个)': ['IPs'],
    'CPU数量(核)': ['CPUs'],
    '可用CPU(核)': ['CPUs'],
    '内存数量(GB)': ['Memory(GB)'],
    '可用内存(GB)': ['Memory(GB)'],
    '确定删除？': ['Confirm to delete?'],
    '原地升级': ['Upgrade in place'],
    '请填写内容': ['Please Enter Content'],
    '请填写正确的JSON格式字符串': ['Please fill in the correct JSON format string'],
    'Kube-proxy代理模式：': ['Kube-proxy: '],
    // 变量的使用 $t('test', { vari1: 1, vari2: 2 })
    'test': ['{vari1} ---english--- {vari2}']
}
