/**
 * Tencent is pleased to support the open source community by making 蓝鲸智云PaaS平台社区版 (BlueKing PaaS Community Edition) available.
 * Copyright (C) 2017-2019 THL A29 Limited, a Tencent company. All rights reserved.
 * Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://opensource.org/licenses/MIT
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */

export default {
    '节点': ['Nodes'],
    '设置标签': ['Set Label'],
    '复制IP': ['Copy IP'],
    '复制所选IP': ['Copy Selected IP'],
    '复制当前页IP': ['Copy Page IP'],
    '复制所有IP': ['Copy All IP'],
    '复制所有IP成功': ['Copy All IP Success'],
    '复制当前页IP成功': ['Copy Page IP Success'],
    '复制 {len} 个IP成功': ['Copy {len} IP Success'],
    '全部集群': ['All Clusters'],
    '清除': ['Clear'],
    '刷新': ['Refresh'],
    '主机名/IP': ['Hostname/IP'],
    '状态': ['Status'],
    '所属集群': ['Cluster'],
    '标签': ['Label'],
    '操作': ['Operation'],
    '初始化中': ['initializing'],
    '删除中': ['removing'],
    '展开': ['expand'],
    '收起': ['collapse'],
    '更多操作': ['More Operation'],
    '初始化失败': ['initial failed'],
    '移除失败': ['remove failed'],
    '不可调度': ['Unschedulable'],
    '不正常': ['Unnormal'],
    '正常': ['Normal'],
    '无数据': ['No Data'],
    '键': ['Key'],
    '值': ['Value'],
    '为什么会有混合值': ['Why are there mixed values'],
    '已选节点的标签中存在同一个键对应多个值': ['The same key corresponds to multiple values in the label of the selected node.'],
    '混合值': ['Mixed value'],
    '保存': ['Save'],
    '取消': ['Cancel'],
    '请选择节点': ['Please Choose Node'],
    '键值【{key}】重复，请重新填写': ['Key value【{key}】is repeated, please re-fill'],
    '没有数据': ['No Data'],
    '确认': ['OK'],
    'IP地址': ['IP Addr'],
    '请输入要搜索的ip，多个ip以 | 隔开': ['Please enter IP to search, multiple IPs separated by |'],
    '请输入要搜索的key': ['Please enter key to search'],
    '请输入要搜索的value': ['Please enter value to search'],
    '集群': ['Clusters'],
    '快速入门': ['Quick Start'],
    '返回': ['Back'],
    '总览': ['Overview'],
    '节点管理': ['Node Manage'],
    '集群信息': ['Cluster Info'],
    '添加节点': ['Add node'],
    '启用Helm': ['Enable Helm'],
    '删除': ['Delete'],
    '您需要删除集群内所有节点后，再进行集群删除操作': ['You need to delete all nodes in the cluster before you do the cluster delete'],
    '申请使用权限': ['Apply permission'],
    '正在删除中，请稍等···': ['Deleting'],
    '查看日志': ['Show Log'],
    '删除失败，请重试': ['Delete failed, please try again'],
    '重新删除': ['Re-delete'],
    '正在初始化中，请稍等···': ['Initializing'],
    '初始化失败，请重试': ['Initialization failed, please try again'],
    '恭喜，集群创建成功！': ['Congratulations, Cluster was created successfully!'],
    'CPU使用率': ['CPU Usage'],
    'CPU占集群使用率': ['CPU Usage for cluster'],
    '内存使用率': ['Memory Usage'],
    '内存使用量': ['Memory Usage'],
    '内存占集群使用率': ['Memory Usage for cluster'],
    '容器requests cpu占集群的使用率': ['Container requests cpu accounted for cluster usage'],
    '容器requests 内存占集群的使用率': ['Container requests memory accounted for cluster usage'],
    '磁盘使用率': ['Disk Usage'],
    '点击新建集群': ['Create Cluster'],
    '欢迎使用容器服务': ['Welcome to the BCS'],
    '使用容器服务，蓝鲸将为您快速搭建、运维和管理容器集群，您可以轻松对容器进行启动、停止等操作，也可以查看集群、容器及服务的状态，以及使用各种组件服务。': ['BCS will quickly build, operate, and manage container clusters for you, making it easy to start, stop, and more, as well as view the status of clusters, containers, and services, as well as use a variety of component services.'],
    '请点击了解更多': ['Read More'],
    '创建容器集群': ['Create Cluster'],
    '快速入门指引': ['Quick Start Guide'],
    '暂无日志信息': ['No Log Data'],
    '操作成功': ['Operation Successful'],
    '操作失败': ['Operation failed'],
    '正在加载中...': ['Loading...'],
    '查看详情': ['Show Detail'],
    '点击了解更多': ['Read More'],
    '确定删除集群？': ['Are you sure want to delete the cluster?'],
    '此操作无法撤回，请确认：': ['This operation can\'t be recalled, please confirm:'],
    '确定': ['Ok'],
    '将master主机归还到你业务的空闲机模块': ['Return the master host to your business\'s idle machine module'],
    '清理其它容器服务相关组件': ['Clean up other container service related components'],
    '启用Helm成功': ['Enable Helm successfully'],
    '启用Helm失败': ['Enable Helm failed'],
    '使用中': ['Using'],
    '未使用': ['Unused'],
    '命名空间': ['Namespace'],
    '已使用': ['Used'],
    '总量': ['Total'],
    '批量操作': ['Batch operation'],
    '允许调度': ['Allow schedule'],
    '停止调度': ['Stop schedule'],
    '容器数量': ['Containers'],
    '升序': ['Asc'],
    '降序': ['Desc'],
    '删除失败': ['delete failed'],
    '故障移除': ['Fault removal'],
    '重试': ['Retry'],
    '强制删除': ['Forced delete'],
    '请确保该节点已经没有运行中的容器': ['Make sure the node has no running containers'],
    '更多': ['More'],
    'pod迁移': ['Pod migration'],
    'taskgroup迁移': ['Taskgroup migration'],
    '按照规则修改主机名': ['Modify the host name according to the rules'],
    '安装容器服务相关的组件': ['Install container service related components'],
    '选择服务器': ['Select Host'],
    '请选择服务器': ['Please Select Host'],
    '关联业务：': ['Associated business: '],
    '主机名称': ['Host Name'],
    '内网IP': ['Inner IP'],
    'Agent状态': ['Agent Status'],
    '您在当前业务下没有主机资源，请联系业务运维': ['You have no host resources under the current service. Please contact the service operation.'],
    '此操作需要对你的主机进行如下操作，请知悉：': ['This operation needs to do the following for your host:'],
    '确定，添加节点': ['Ok'],
    '我再想想': ['Cancel'],
    '删除中...': ['removing'],
    '内存': ['RAM'],
    '磁盘IO': ['Disk IO'],
    '磁盘': ['Disk'],
    '前置检查': ['Pre-inspection'],
    '添加中...': ['Adding'],
    '初始化中...': ['initializing'],
    '启用中...': ['Enable...'],
    '停用中...': ['Disable...'],
    '迁移中...': ['Migration...'],
    '操作中...': ['Operation...'],
    '基本信息': ['Basic Information'],
    '集群名称': ['Cluster Name'],
    '请输入集群名称，不超过64个字符': ['Please enter the cluster name, no more than 64 characters'],
    '集群ID': ['Cluster ID'],
    'Master数量': ['Master count'],
    '节点数量': ['Node count'],
    '所属地域': ['Region'],
    '创建时间': ['Create Time'],
    '更新时间': ['Update Time'],
    '集群描述': ['Cluster Desc'],
    '设置变量': ['Set Variable'],
    '配置': ['Configuration'],
    '集群变量': ['Cluster Variable'],
    '变量：': ['Variable: '],
    '请输入集群描述，不超过128个字符': ['Please enter the cluster desc, no more than 120 characters'],
    'Master信息': ['Master Info'],
    '当前节点已被项目（{projectName}）的集群（{clusterName}）占用': ['The current node is already occupied by the cluster（{clusterName}）of the project（{projectName}）'],
    '无匹配的主机资源': ['No matching host resources'],
    '当前访问的页面不存在': ['Currently accessed page does not exist'],
    '当前访问的集群不存在': ['The currently accessed cluster does not exist'],
    'Sorry，您的权限不足!': ['Sorry, your permissions are not enough!'],
    '操作审计': ['Operation Audit'],
    '操作对象类型': ['Operation object type'],
    '操作类型': ['Operation Type'],
    '类型：': ['Type：'],
    '全部1': ['all', '全部'],
    '注意1': ['note', '注意'],
    '创建1': ['add', '创建'],
    '更新1': ['modify', '更新'],
    '删除1': ['delete', '删除'],
    '开始1': ['begin', '开始'],
    '结束1': ['end', '结束'],
    '启动1': ['start', '启动'],
    '暂停1': ['pause', '暂停'],
    '继续1': ['carryon', '继续'],
    '停止1': ['stop', '停止'],
    '重启1': ['restart', '重启'],
    '查询1': ['query', '查询'],
    '未知1': ['unknown', '未知'],
    '完成1': ['completed', '完成'],
    '错误1': ['error', '错误'],
    '处理中1': ['busy', '处理中'],
    '成功1': ['succeed', '成功'],
    '失败1': ['failed', '失败'],
    '查询': ['Search'],
    '时间': ['Time'],
    '对象及类型': ['Object and Type'],
    '发起者': ['Operator'],
    '对象：': ['Object：'],
    '描述': ['Desc'],
    '事件查询': ['Event Query'],
    '事件对象': ['Event Object'],
    '事件级别': ['Event Level'],
    '组件': ['Component'],
    '对象及级别': ['Object&Level'],
    '事件内容': ['Event Content'],
    '级别：': ['Level：'],
    '昨天': ['Yestoday'],
    '最近一周': ['Last week'],
    '最近一个月': ['Last month'],
    '最近三个月': ['Last 3 months'],
    '公共镜像': ['Public Image'],
    '项目镜像': ['Private Image'],
    '如何推镜像？': ['How to push image?'],
    '输入镜像名，按Enter搜索': ['Press Enter to search image name'],
    '来源：': ['Source：'],
    '简介：': ['Introduction：'],
    '详情': ['Details'],
    '次下载': ['downloads'],
    '最近更新人': ['Latest updater'],
    '最近更新时间': ['Latest update time'],
    '仓库相对地址': ['Repo relative address'],
    '名称': ['Name'],
    '大小': ['Size'],
    '地址': ['Address'],
    '没有更多TAG': ['No more TAGs'],
    '主机名称：': ['Hostname：'],
    '主机IP：': ['HostIP：'],
    '容器IP：': ['ContainerIP：'],
    '容器ID：': ['ContainerID：'],
    '镜像：': ['Image：'],
    '网络模式：': ['Network mode：'],
    '网络': ['Network'],
    '存储使用率': ['Disk usage'],
    '端口映射': ['Port Mapping'],
    '该应用的网络模式无需端口映射': ['The application\'s network mode does not require port mapping'],
    '命令': ['command'],
    '挂载卷': ['Mounted volume'],
    '环境变量': ['Env variable'],
    '健康检查': ['Health check'],
    '资源限制': ['Resource limit'],
    '正在加载': ['Loading'],
    '发送': ['Send'],
    '接收': ['Receive'],
    '当前节点上正在运行的容器会被调度到其它可用节点': ['Containers running on the current node are scheduled to other available nodes'],
    '清理容器服务系统组件': ['Clean up container service system components'],
    '仅删除节点的信息记录，需要手动清理节点及其服务': ['Delete only the information record of the node, you need to manually clean up the node and its services.'],
    '确认要重新初始化节点【{innerIp}】？': ['Confirm want to reinitialize the node【{innerIp}】?'],
    '确认要强制删除节点【{innerIp}】？': ['Confirm want to delete the node【{innerIp}】?'],
    '确认要删除节点【{innerIp}】？': ['Confirm want to delete the node【{innerIp}】?'],
    '确认允许调度节点【{innerIp}】？': ['Confirm want to allow schedule the node【{innerIp}】?'],
    '确认要停止调度节点【{innerIp}】？': ['Confirm want to stop schedule the node【{innerIp}】?'],
    '确定删除节点？': ['Confirm want to delete the node?'],
    '确定强制删除节点？': ['Confirm want to delete the node?'],
    '确定移除故障节点：{innerIp}？': ['Confirm to remove the failed node: {innerIp}?'],
    '确定移除故障节点？': ['Confirm to remove the failed node'],
    '重置': ['Reset'],
    '请输入集群名称': ['Please enter the cluster name'],
    '必填项，不超过64个字符': ['Required, no more than 64 characters'],
    '集群描述：': ['Desc: '],
    '请输入集群描述': ['Please enter the cluster desc'],
    '必填项，不超过128个字符': ['Required, no more than 128 characters'],
    '选择Master：': ['Select Master: '],
    '已选服务器': ['Selected Host'],
    '序号': ['No.'],
    '注意事项：': ['Notice: '],
    '服务器将按照系统规则修改主机名': ['Server will modify the host name according to the system rules'],
    '修改后': ['After Modify'],
    '服务器将安装容器服务相关组件': ['Server will install the container service related components'],
    '请选择奇数个服务器': ['Please select odd number of servers'],
    '移除': ['Delete'],
    '名称：': ['Name: '],
    '内存：': ['RAM：'],
    '存储：': ['Disk：'],
    'IP来源：': ['IP Source：'],
    '内核：': ['Core：'],
    '操作系统：': ['OS：'],
    '1小时': ['1hour'],
    '24小时': ['24hours'],
    '近7天': ['Last 7 days'],
    '容器': ['Container'],
    '镜像': ['Image'],
    '容器状态不是running': ['Container status is not running'],
    '异常': ['abnormal'],
    '错误': ['Error'],
    '创建集群': ['Create Cluster'],
    '确定，创建集群': ['Ok'],
    '确定要离开？数据未保存，离开后将会丢失': ['Data is not saved and will be lost after leaving, Are you sure?'],
    '请确认注意事项内容': ['Please confirm the contents of the notice'],
    '下发集群配置中，请稍候...': ['In the cluster configuration, please wait...'],
    '下发集群配置完成': ['The cluster configuration is complete.'],
    '蓝鲸容器服务使用教程': ['BCS Use Tutorial'],
    '本教程将向您简单介绍如何使用蓝鲸容器服务': ['This tutorial will give you a brief introduction to how to use the BCS.'],
    '以下是您操作的主要步骤：': ['Here are the main steps for your operation:'],
    '1、新建集群': ['1. Create Cluster'],
    '点击导航“集群”': ['Click navigation "cluster"'],
    '“新建集群”，需要选择Master节点主机（主机信息来源于CMDB），创建集群，确定创建后，系统将进行集群初始化操作': ['"Create Cluster", you need to select the master node host (the host information comes from the CMDB), create a test cluster or a prod cluster. After the creation is complete, the system will perform the cluster initialization operation.'],
    '2、集群增加Node节点': ['2. Cluster adds Node nodes'],
    '进入指定集群': ['Enter the specified cluster'],
    '节点管理，选择添加节点即可': ['Node Manage, choose to add a node'],
    '3、项目镜像管理': ['3. Private image management'],
    '点击导航“仓库”': ['Click navigation "ImageHub"'],
    '“项目镜像”，按文档“如何推镜像”指引将项目镜像推至仓库': ['"Private Image", push the private image to the ImageHub according to the document "How to push the image" guide'],
    '继续': ['Continue'],
    '关闭': ['Close'],
    '4、创建命名空间': ['4. Create Namespace'],
    '点击导航“命名空间”，新建命名空间，指定命名空间所属集群': ['Click navigation "Namespaces" to create namespace and specify the cluster to which the namespace belongs.'],
    '5、创建模板集': ['5. Create Templateset'],
    '点击导航“模板集”，新建模板集。': ['Click navigation "TemplateSets" to create templateset.'],
    '模板集指您接入容器服务的业务模块所包含的Mesos或Kubernetes资源配置，我们将以模板的形式供您可持续编辑，分版本保存。': ['Templateset refers to the Mesos or Kubernetes resource configuration contained in the business module of your access to the container service. We will provide you with a template for sustainable editing and version saving.'],
    '您可以通过Json或Yaml文件导入的方式将已有服务的资源配置导入模板，再次进行编辑并保存': ['You can import the resource configuration of an existing service into the template by JSON or Yaml file import, edit it again and save it.'],
    '6、模板实例化': ['6. Template instantiation'],
    '保存模板后，点击实例化按钮，选择模板集、具体资源模板以及指定集群的命名空间，系统将生成对应的资源配置文件（Json\Yaml）供您检查。': ['After saving the template, click "instantiation" button, select the templateset, the specific resource template, and the namespace of the specified cluster. The system will generate the corresponding resource configuration file (Json\Yaml) for you to check.'],
    '点击“创建”按钮后，系统将下发资源配置文件到指定集群，创建应用实例。': ['After clicking the "Create" button, the system will deliver the resource configuration file to the specified cluster to create an application instance.'],
    '7、应用实例详情': ['7. Application Instance Details'],
    '点击导航“应用”，您将看到具体的实例信息，可在线做滚动升级、扩缩容等操作。': ['Click navigation "Applications", you will see the specific instance information, you can do online rolling updates, expansion and contraction operations.'],
    '重新初始化': ['Re-initialization'],
    '提示': ['Tip'],
    '执行中': ['Executing'],
    '取消中': ['Cancel'],
    '请输入IP，按Enter搜索': ['Press Enter to search IP'],
    '清空': ['Clear'],
    '搜索': ['Search'],
    '多个IP以空格分开，按回车搜索': ['Multiple IPs are separated by spaces, press Enter to search'],

    '新建': ['Create'],
    '命名空间创建后不可更改': ['Not changed after created'],
    '变量': ['Variable'],
    '设置变量值': ['Set variable value'],
    '所属集群：': ['Cluster：'],
    '请输入': ['Please Enter'],
    '请选择': ['Please Select'],
    '新建命名空间': ['Create Namespace'],
    '请填写命名空间名称': ['Please fill the namespace name'],
    '命名空间名称不得小于2个字符': ['Namespace name must be at least 2 characters'],
    '命名空间名称只能包含小写字母、数字以及连字符(-)，且不能以数字开头': ['Namespace names can only contain lowercase letters, numbers, and hyphens (-), and cannot begin with a number'],
    '请选择所属集群': ['Please select the cluster to which you belong'],
    '修改命名空间：{nsName}': ['Update Namespace: {nsName}'],
    '确定删除命名空间？': ['Confirm want to delete the namespace?'],
    '输入关键字，按Enter搜索': ['Press Enter to search keyword'],
    '集群列表': ['Clusters'],
    '命名空间列表': ['Namespaces'],
    '删除命名空间': ['Delete namespace'],
    '删除Namespace将销毁Namespace下的所有资源，销毁后所有数据将被清除且不可恢复，请提前备份好数据。': ['Delete Namespace will destroy all resources under the Namespace. Then all data will be cleared and cannot be restored. Please backup the data.'],
    '删除Namespace成功': ['Delete namespace successfully'],
    '集群就绪后，您可以创建命名空间、推送项目镜像到仓库，然后通过服务配置模板集或使用Helm部署服务': ['Once the cluster is ready, you can create a namespace, push the project image to the repository, then configure the template set through the service or deploy the service using Helm'],
    '集群就绪后，您可以创建命名空间、推送项目镜像到仓库，然后通过服务配置模板集部署服务': ['Once the cluster is ready, you can create a namespace, push the project image to the warehouse, and then deploy the service through the service configuration templateset'],

    'HPA管理': ['HPA Manage'],
    '批量删除': ['Batch Delete'],
    '当前': ['Current'],
    '目标': ['Target'],
    '实例数': ['Instances'],
    '范围': ['Scope'],
    '关联资源': ['Relevant resource'],
    '来源': ['Source'],
    '创建人': ['Creator'],
    '已选': ['Selected'],
    '条': ['Item'],
    '确定要删除以下': ['Sure you want to delete'],
    '请选择要删除的HPA！': ['Please choose to delete the HPA!'],
    '确定要删除HPA': ['Sure you want to delete HPA!'],
    '删除成功': ['Successfully delete'],

    'Service名称': ['Service Name'],
    'Service类型': ['Service Type'],
    '更新人': ['Modifier'],
    '关联标签': ['Relevant Label'],
    '请选择要关联的Application': ['Please select the Associated App'],
    '请关联相应的Application': ['Please associate app'],
    '协议': ['Protocol'],
    '端口名称': ['Port Name'],
    '目标端口': ['Target Port'],
    '点此': ['Click this'],
    '去模板集配置端口映射信息': [' to Templateset setting port mapping'],
    '请关联相应的应用': ['Please associate app'],
    '请选择要关联的应用': ['Please associate app'],
    '标签管理': ['Label Manage'],
    '备注管理': ['Remark Manage'],
    '保存并更新': ['Save and update'],
    '请先关联应用': ['Please associate app'],
    '关联的应用没有公共的标签（注：Key、Value都相同的标签为公共标签）': ['There is no public label for associated app (ps: Key、Value all same are the public label)'],
    '基础信息': ['Basic information'],
    '选择器': ['Selector'],
    '确定要删除以下Service？': ['Sure you want to delete Service?'],
    '更新Service': ['Update Service'],
    'ClusterIP不为None时，请配置相应的端口映射': ['ClusterIP is not None, please setting your port mapping'],
    '端口不能为空': ['Port can not be empty'],
    '请选择协议': ['Please select protocol'],
    '端口名称以小写字母开头，只能包含：小写字母、数字、连字符(-)，长度小于30个字符': [''],
    'NodePort的范围为30000-32767': ['The range is 30000-32767 for NodePort'],
    '确定要删除Service': ['Sure you want to delete Service'],

    '权重设置': ['Weight Setting'],
    '输入': ['Input'],
    '服务端口': ['Service Port'],
    '域名': ['Domain'],
    '路径': ['Path'],
    '关联LoadBalance': ['Associate LoadBalance'],
    '没有相关联的 LoadBalance，请先到 网络 -> LoadBalance 页面关联': ['if there is no LoadBalance, please go Network/LoadBalance to setting'],
    '端口索引': ['Port Index'],
    '权重的值为大于等于0的整数，且所有权重相加为100': ['The weight is an integer greater than or equal to 0, and the weights are added to 100.'],
    '服务端口不能为空': ['Service port cannot be empty'],
    '服务端口范围为1-65535': ['Service port range is 1-65535'],
    '请填写正确的路径': ['Please fill in the correct path'],
    '请选择需要关联的LoadBalance': ['Please select the LoadBalance you need to associate'],
    '负载均衡算法': ['Load Balancing Algorithm'],

    '新建LoadBalance': ['New LoadBalance'],
    '网络类型': ['Network Type'],
    '转发模式': ['Forwarding Mode'],
    'IP集': ['IP Set'],
    '镜像地址': ['Image Address'],
    '镜像版本': ['Image Version'],
    '实例数量': ['Instances Number'],
    '调度约束': ['Scheduling Constraint'],
    '多个值以管道符分隔': ['Multiple values ​​separated by pipe'],
    '网络模式': ['Network Mode'],
    '自定义值': ['Custom value'],
    '网卡': ['Network Card'],
    '编辑LoadBalance': ['Edit LoadBalance'],
    '确定要启动此LoadBalance': ['Sure to start this LoadBalance'],
    '已经将配置文件下发到后台，请稍后再详情中查看': ['he configuration file has been delivered to the background, please check the details later'],
    '确定要停止此LoadBalance': ['Sure to stop this LoadBalance'],
    '确定要删除LoadBalance': ['Sure to delete this LoadBalance'],
    '名称错误，只能包含：小写字母、数字、连字符(-)，必须是字母开头，长度小于30个字符': ['The name is incorrect and can only contain: lowercase letters, numbers, hyphens (-), must be at the beginning of the letter, and the length is less than 30 characters'],
    '请选择镜像版本': ['Please select the image version'],
    '请输入正确IP地址': ['Please enter the correct IP address'],
    'IP数量和实例数量不相等': ['The number of IPs and the number of instances are not equal'],
    '请填写实例数量！': ['Please enter the instances number'],
    '请填写网卡': ['Please enter network card'],
    'BRIDGE网络模式下，端口必填': ['In BRIDGE network mode, the port is required'],
    '数据保存成功': ['The data is saved successfully'],
    '查看': ['View'],
    '停止': ['Stop'],
    '启动': ['Start'],
    '编辑': ['Edit'],
    '流量': ['Flow'],
    '入带宽': ['Incoming Bandwidth'],
    '出带宽': ['Outgoing Bandwidth'],
    '所属namespace': ['Namespace'],
    '调度约束规则': ['Constraint Rule'],
    '映射Taskgroup': ['Map Taskgroup'],
    '设置协议': ['Setting Protocol'],
    '至少有一个勾选': ['At least one check'],
    '启用Http': ['Use Http'],
    '启用Https': ['Use Https'],
    '节点IP': ['Node IP'],
    '确定要删除LoadBalance？': ['Sure to delete this LoadBalance?'],
    '请选择命名空间': ['Please select Namespace'],
    '请输入http端口': ['Please enter http port'],
    '请输入https端口': ['Please enter http ports'],
    '请添加节点': ['Please add a node'],

    '输入命名空间，按Enter搜索': ['Enter namespace and press Enter'],
    '输入名称或命名空间，按Enter搜索': ['Enter keyword and press Enter'],
    '明文显示': ['Text display'],
    '隐藏': ['Text hide'],
    '显示标签': ['Show Label'],
    '未命名': ['Unnamed'],
    '添加Key': ['Add Key'],
    '值来源': ['Value source'],
    '在线编辑': ['Online Editing'],
    '仓库获取': ['Warehouse'],
    '请输入键': ['Please enter the key'],
    '的内容': [''],
    '请输入仓库中配置文件的相对路径': ['Please enter the relative path of the configuration file in the repository'],
    '实例化时会将值的内容做base64编码': ['The content of the value is base64 encoded when instantiated'],
    '确定要删除以下Configmap？': ['Sure to delete this Configmap?'],
    '请选择要删除的Configmap': ['Please select the Configmap to delete'],
    '更新': ['Update '],
    '确定要删除Configmap': ['Sure to delete this Configmap'],
    '重复': ['repeat'],
    '更新成功': ['update completed'],
    '键名错误，只能包含：字母、数字、连字符(-)、点(.)、下划线(_)，首字母必须是字母，长度小于30个字符': ['The key name is incorrect and can only contain: letters, numbers, hyphens (-), dots (.), underscores (_), the first letter must be a letter, and the length is less than 30 characters'],
    '键不可重复': ['Key can not be repeatd'],
    '确定要删除以下Secret？': ['Sure to delete this Secret?'],
    '请选择要删除的Secret': ['Please select the Secret to delete'],
    '确定要删除Secret': ['Sure to delete this Secret'],
    '主机列表': ['Host List'],
    '主机名': ['Host Name'],
    '规则': ['Rule'],
    '服务名称': ['Service Name'],
    '确定要删除以下Ingress？': ['Sure to delete this Ingress'],
    '请选择要删除的Ingress': ['Please select the Ingress to delete'],
    '确定要删除Ingress': ['Sure to delete this Ingress'],
    '变量管理': ['Variable Manage'],
    '新增变量': ['Add Variable'],
    '变量名称': ['Variable Name'],
    '默认值': ['Defaults'],
    '作用范围': ['Scope'],
    '引用处': ['Reference'],
    '批量更新': ['Batch Update'],
    '系统内置变量，不能编辑': ['System variables, can not edit'],
    '系统内置变量': ['System Variable'],
    '已经被引用，不能删除': ['Already referenced, cannot be deleted'],
    '所属': ['Belong'],
    '确定要删除以下变量？': ['Sure to delete this Variable?'],
    '全局变量': ['Global Variable'],
    '命名空间变量': ['Namespace Variable'],
    '说明': ['Description'],
    '提交': ['Submit'],
    '被引用位置': ['Referenced'],
    '上下文': ['Context'],
    '全部作用范围': ['All Scope'],
    '编辑变量': ['Edit Variable'],
    '请选择要删除的变量': ['Please select the Variable to delete'],
    '确定要删除变量': ['Sure to delete this Variable'],
    '请输入变量名称': ['Please Input the Variable name'],
    '请输入32个字符以内的变量名称': ['Please enter a variable name within 32 characters'],
    '请输入变量KEY': ['Please input the Variable key'],
    'KEY 只能包含字母、数字和下划线，且以字母开头，最大长度为64个字符': ['KEY can only contain letters, numbers, and underscores, starting with a letter and having a maximum length of 64 characters'],
    '变量创建成功': ['Variable created successfully'],
    '变量更新成功': ['Variable update succeeded'],
    '变量删除成功': ['Variable delete succeeded'],
    '请输入32个字符以内的名称': ['Please enter a name within 32 characters'],
    '集群IP': ['Cluster IP'],
    '您可以在模板集中使用': ['you can use'],
    '来引用该变量': ['to import this Variable'],
    '变量KEY': ['Variable Key'],
    '模板实例化操作即平台通过用户配置的模板，生成对应的资源json文件，并将它们下发到指定集群的命名空间下。资源创建成功后，可在"应用"和"网络"中查看资源实例详情。': ['Template instantiation means that the platform generates the corresponding resource json files through the user-configured templates and sends them to the namespace of the specified cluster. After the resource is created successfully, you can view the resource instance details in Application and Network.'],
    '模板实例化操作即平台通过用户配置的模板，生成对应的资源yaml文件，并将它们下发到指定集群的命名空间下。资源创建成功后，可在"应用"和"网络"中查看资源实例详情。': ['Template instantiation means that the platform generates the corresponding resource yaml files through the user-configured templates and sends them to the namespace of the specified cluster. After the resource is created successfully, you can view the resource instance details in Application and Network.'],
    '同步命名空间': ['Sync Namespace'],
    '同步非本页面创建的命名空间数据': ['Synchronize namespace not created by this page'],
    '同步命名空间任务已经启动，请稍后刷新': ['The sync namespace task has started, please refresh later'],
    '类型': ['Type'],
    '导出': ['Export'],

    '已选择{remainCount}个节点': ['{remainCount} items'],
    '点击查看原因': ['Click to view the reason'],
    '请注意：命名空间{name}下的同名资源将会被覆盖更新，确认创建？': ['Please note: the resource with the same name under the namespace {name} will be overwritten and updated to confirm the creation?'],
    '表单模式': ['Form mode'],
    '提示：容器端口是容器内部的Port。在配置Service的端口映射时，通过"目标端口"进行关联，从而暴露服务': ['Tip: The container port is the port inside the container. When configuring the port mapping of the Service, the association is made through the "target port" to expose the service'],
    '提示：项目镜像不存在，': ['Tip: The project image does not exist,'],
    '去创建': ['To create'],
    '管理Metric': ['Manage Metric'],
    '更新过程中能够进入不可用状态的 Pod 的最大个数': ['The maximum number of Pods that can enter the unavailable state during the update process'],
    '更新过程中能够额外创建的 Pod 的最大个数': ['The maximum number of Pods that can be additionally created during the update process'],
    '刷新镜像列表': ['Refresh images'],
    '请先在"Pod模板设置" -> "卷"中设置': ['Please set it in "Pod Template Settings" -> "Volumes" first'],
    '引用端口映射中的端口设置': ['Refer to the port settings in the port map'],
    '端口映射示例': ['Port mapping example'],
    '应用Container': ['Application Container'],
    '用于在启动应用Container之前，启动一个或多个“初始化”容器，完成应用Container所需的预置条件': ['Used to start one or more "initialize" containers and complete the pre-conditions required to apply the container before launching the application container'],
    '提示：同一个虚拟主机名可以有多个路径': ['Tip: The same virtual hostname can have multiple paths'],
    '暂无数据': ['No data'],
    '无匹配数据': ['No matching data'],

    '容器服务未启用': ['Container service is not enabled'],
    '，请完善以下信息': [', complete information'],
    '业务编排类型': ['Business orchestration type'],
    '当前账号无有权限的业务，请到': ['If the current account has no permission, please go to '],
    '权限中心': ['authority center '],
    '申请，': ['apply, '],
    '查看帮助': ['view help'],
    '您当前的项目': ['Your current project '],
    '资源': ['Resource'],
    '需要的权限': ['Required permissions'],
    '去申请': ['Apply'],
    '无权限操作': ['No permission operation'],
    '新建证书': ['New certificate'],
    '编辑证书': ['Edit certificate'],
    '请输入名称，英文大小写、数字、下划线和英文句号，最大长度为64个字符': ['Please enter a name, English case, number, underscore and period, the maximum length is 64 characters'],
    '请输入证书': ['Please enter a certificate'],
    '请输入私钥': ['Please enter the private key'],
    '确认要删除证书': ['Sure to delete the certificate'],
    '请输入Name': ['Please enter Name'],
    'Name错误，只能包含英文大小写、数字、下划线和英文句号': ['Name error, can only contain English capitalization, numbers, underscores and periods'],
    '请输入Cert': ['Please enter Cert'],
    '请输入Key': ['Please enter Key'],
    '更新证书成功': ['Update certificate successfully'],
    '创建证书成功': ['Successful certificate creation'],
    '同步仓库中的Helm Chart': ['Synchronous Helm Chart'],
    '通过Helm Chart、Client、模板集YAML模式创建的应用，请通过命名空间视图查询详情': ['For applications created by Helm Chart, Client, and template set YAML mode, please query the details through the namespace view'],
    '展示通过模板集表单模式实例化的应用详情': ['Show application details instantiated through template set form mode'],
    '共包含': ['Include'],
    '个应用模板': ['templates'],
    '展示通过命名空间页面创建的命名空间的应用详情': ['Show application details for namespaces created through namespace pages'],
    'Sorry，您的权限不足！': ['Sorry, your permissions are not enough!'],
    '页面找不到了！': ['The page could not be found!'],
    '服务器维护中，请稍后重试!': ['In server maintenance, please try again later!'],
    '功能正在建设中···': ['The function is under construction···'],
    '请确认以上内容，才可操作': ['Please confirm the above to operate'],
    '启用容器服务': ['Enable BCS'],
    '所属集群/命名空间': ['Cluster/Namespace'],
    '更新/创建时间': ['Update/Create Time'],
    '访问方式': ['Access'],
    '其他信息': ['Other Info'],
    '集群内访问': ['Access Internal'],
    '集群外访问': ['Access External'],
    'CL5路由': ['CL5 Router'],
    '新建CL5': ['Create CL5'],
    '业务模块': ['Business Module'],
    '责任人': ['Responsible Person'],
    '请输入业务模块': ['Please Enter Business Module'],
    '当前功能在灰度中，请联系容器助手下发CL5 controller才能生效': ['Please contact BCS assistant to take effect.'],
    '请填写业务模块': ['Please Enter Business Module'],
    'Node节点所属的CMDB三级业务模块ID': ['CMDB Level 3 Business Module ID to which the Node belongs'],
    '入流量': ['Network Receive'],
    '出流量': ['Network Transmit'],
    '磁盘写数据': ['Disk Write'],
    '磁盘读数据': ['Disk Read'],
    '阈值': ['Threshold'],
    '网络使用率': ['Network Usage'],
    'IO使用率': ['IO Usage'],
    '磁盘IO总量': ['DiskIO Total'],
    '回滚上一版本': ['Rollback previous version'],
    '当前版本配置': ['Current Config'],
    '上一版本配置': ['Previous Config'],
    '{instanceName}回滚上一版本': ['{instanceName} rollback previous version'],
    '确定回滚上一版本【{instanceName}】？': ['Confirm to rollback previous version [{instanceName}]?'],
    '回滚中...': ['Rollbacking'],
    'TKE集群ID': ['TKE Cluster ID'],
    '集群版本': ['Cluster Version'],
    'Pod总量': ['Total Pod'],
    'Service数量上限/集群': ['Maximum number of services'],
    'Pod数量上限/节点': ['Number of Pods per node'],
    '重新添加': ['ReInstall'],
    '所选节点均处于初始化失败状态时才允许此操作': ['Allow this operation only if the selected nodes are in an initialization failure state'],

    '规则"{name}"的Service名称：请选择Service名称': ['Service name for rule "{name}": Please select a service name'],
    '规则"{name}"的协议：请选择协议': ['Protocol for rule "{name}": Please select a protocol'],
    '规则"{name}"的端口：请选择端口': ['Port for rule "{name}": Please select a port'],
    '规则"{name}"的会话保持时间：会话保持时间范围为30-3600': ['Session hold time for rule "{name}": Session hold time range is 30-3600'],
    '规则"{name}"的会话保持时间：请输入会话保持时间': ['Session hold time for rule "{name}": Please enter a session hold time'],
    '规则"{name}"的监听CLB端口：请输入监听CLB端口': ['CLB port for rule "{name}": Please enter CLB port for listening'],
    '负载均衡策略': ['Load balancer strategy'],
    '健康检查策略': ['Health check strategy'],
    '已启用': ['activated'],
    '未启用': ['Not activated'],
    '添加规则': ['Add Rule'],
    '监听CLB端口': ['CLB Port'],
    '会话保持时间': ['Session Hold Time'],
    '响应超时时间': ['Response Timeout'],
    '探测间隔时间': ['Detection Interval'],
    '探测路径': ['Detection Path'],
    '健康状态码': ['Health Status Code'],
    '开启Https': ['Use Https'],
    '认证模式': ['Authentication Mode'],
    '证书ID': ['Certificate ID'],
    '不可删除': ['Cannot be delete'],
    'Kubernetes官方维护的Ingress Controller': ['Kubernetes Officially Maintained Ingress Controller'],
    'K8S官方维护的ingress-nginx': ['K8S officially maintained ingress-nginx'],
    '请选择CLB': ['Please select CLB'],
    '请选择区域': ['Please select a region'],
    '客户端证书ID': ['CertCaId'],
    '客户端证书的 ID，如果 mode=mutual，监听器如果不填写此项则必须上传客户端证书，包括 certClientCaName，certCilentCaContent': ['CertCaId. If mode = mutual, the listener must upload the client certificate if it is not filled in, including certClientCaName, certCilentCaContent'],
    '请通过模板集创建Ingress': ['Please create an Ingress from a TemplateSet'],

    '访问权限': ['Access Mode'],
    '回收策略': ['Reclaim Policy'],
    '云盘类型': ['Cloud Type'],
    '计费模式': ['Billing'],
    '升级': ['Upgrade'],
    '确定要升级新版本': ['Confirm to Upgrade'],
    '升级大约需要 1~2 分钟，请勿重复提交；升级过程中 Prometheus 服务将会重启，数据无损失': ['Upgrade takes about 1 to 2 minutes and do not repeat submissions; Prometheus service will be restarted without losses'],
    // 变量的使用 $t('test', { vari1: 1, vari2: 2 })
    'test': ['{vari1} ---english--- {vari2}']
}
